[package]
name = "ncc"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
unicode-segmentation = "=1.12.0"

[[bin]]
name = "ncc"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
too_many_lines = "forbid"
needless_pass_by_value = "forbid"
struct_excessive_bools = "forbid"
case_sensitive_file_extension_comparisons = "forbid"
unicode_not_nfc = "forbid"
