[package]
name = "ncc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "=1.0.150", optional = true }

[features]
default = ["lsp"]
lsp = ["dep:serde_json"]

[dev-dependencies]
unicode-segmentation = "=1.12.0"

[[bin]]
name = "ncc"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
