use std::{fs, path::Path, process::Command};

#[test]
fn compiles_and_runs_functions_conditionals_and_output() {
    let source = r#"
        fn classify(int value) int {
          if value {
            0 -> { return 10 }
            _ -> { return 20 }
          }
        }
        test "conditional" {
          assert classify(0) == 10
          assert classify(9) == 20
          @println(classify(0))
        }
    "#;
    let c = ncc::compile_test_source(source, std::path::Path::new("test.nc")).unwrap();
    let directory = std::env::temp_dir().join(format!("ncc-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source_path = directory.join("program.c");
    let executable = directory.join("program");
    fs::write(&source_path, c).unwrap();
    assert!(
        Command::new("cc")
            .arg(&source_path)
            .arg("-o")
            .arg(&executable)
            .status()
            .unwrap()
            .success()
    );
    let output = Command::new(&executable).output().unwrap();
    assert!(output.status.success());
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "10\n");
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn rejects_immutable_assignment() {
    let source = "test \"immutable\" { int value = 1 value = 2 }";
    let error = ncc::compile_test_source(source, std::path::Path::new("test.nc")).unwrap_err();
    assert!(error.to_string().contains("cannot mutate immutable"));
}

#[test]
fn allows_top_level_builtin_calls() {
    let source = "@print(\"Hello world\")";
    ncc::compile_source(source, std::path::Path::new("hello-world.nc")).unwrap();
    let c = ncc::compile_source(source, std::path::Path::new("hello-world.nc")).unwrap();
    assert!(c.contains("fwrite(") && c.contains(", stdout)"));
    assert!(c.contains("\"Hello world\""));
}

#[test]
fn run_does_not_leave_generated_files() {
    let directory = std::env::temp_dir().join(format!("ncc-run-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source = directory.join("hello.nc");
    fs::write(&source, "@print(\"hello\")").unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
        .arg("run")
        .arg(&source)
        .output()
        .unwrap();
    assert!(output.status.success());
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "hello");
    assert!(!directory.join("hello").exists());
    assert!(!directory.join("hello.c").exists());
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn build_only_leaves_the_requested_output() {
    let directory = std::env::temp_dir().join(format!("ncc-build-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source = directory.join("hello.nc");
    let executable = directory.join("greeting");
    fs::write(&source, "@print(\"hello\")").unwrap();
    let status = Command::new(env!("CARGO_BIN_EXE_ncc"))
        .args([
            "build",
            source.to_str().unwrap(),
            "--output",
            executable.to_str().unwrap(),
        ])
        .status()
        .unwrap();
    assert!(status.success());
    assert!(executable.exists());
    assert!(!directory.join("greeting.c").exists());
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn build_format_flag_overrides_the_output_extension() {
    let directory = std::env::temp_dir().join(format!("ncc-format-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source = directory.join("hello.nc");
    fs::write(&source, "@print(\"hello\")").unwrap();
    let c_output = directory.join("generated-without-extension");
    let object_output = directory.join("generated-object");
    let compiler = env!("CARGO_BIN_EXE_ncc");
    assert!(
        Command::new(compiler)
            .args([
                "build",
                source.to_str().unwrap(),
                "--format",
                "C",
                "--output",
                c_output.to_str().unwrap()
            ])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        fs::read_to_string(&c_output)
            .unwrap()
            .contains("Generated by ncc")
    );
    assert!(
        Command::new(compiler)
            .args([
                "build",
                source.to_str().unwrap(),
                "-f",
                "obj",
                "-o",
                object_output.to_str().unwrap()
            ])
            .status()
            .unwrap()
            .success()
    );
    assert!(fs::metadata(&object_output).unwrap().len() > 0);
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn supports_multiple_conditional_patterns() {
    let source = r"
        fn fibonacci(int n) int {
          if n {
            0, 1 -> { return n }
            _ -> { return fibonacci(n - 1) + fibonacci(n - 2) }
          }
        }
        @println(fibonacci(10))
    ";
    let directory = std::env::temp_dir().join(format!("ncc-fibonacci-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source_path = directory.join("fibonacci.nc");
    fs::write(&source_path, source).unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
        .arg("run")
        .arg(&source_path)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "55\n");
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn explains_missing_conditional_arrow() {
    let source = "test \"bad conditional\" { if 1 { 1 { } } }";
    let error = ncc::compile_source(source, std::path::Path::new("bad.nc")).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("expected `->` after conditional pattern(s)")
    );
}

#[test]
fn emits_only_headers_required_by_the_program() {
    let no_headers = ncc::compile_source("fn noop() {}", std::path::Path::new("empty.nc")).unwrap();
    assert!(!no_headers.contains("#include"));

    let print_only =
        ncc::compile_source("@println(\"hello\")", std::path::Path::new("print.nc")).unwrap();
    assert!(print_only.contains("#include <stdio.h>"));
    assert!(!print_only.contains("#include <stdint.h>"));
    assert!(!print_only.contains("#include <stdbool.h>"));
    assert!(!print_only.contains("#include <stdlib.h>"));
    assert!(!print_only.contains("#include <math.h>"));
}

#[test]
fn ordinary_compilation_ignores_tests_before_semantic_processing() {
    let path = std::path::Path::new("ignored.nc");
    for source in [
        "test \"unknown\" { @println(missing) }",
        "test \"type error\" { int value = true }",
        "fn identity<T>(T value) T { return value } test \"generic\" { _ = identity<int, bool>(1) }",
        "test \"embed\" { _ = @embed(\"missing-file\") }",
        "test \"assert\" { assert false }",
        "test \"throw\" { throw \"failure\" }",
    ] {
        ncc::compile_source(source, path).unwrap();
        for release in [false, true] {
            let c = ncc::compile_source_with_options(source, path, release).unwrap();
            assert!(!c.contains("#include"), "{source}");
            let output = ncc::compile_source_with_diagnostics(source, path, release).unwrap();
            assert_eq!(
                output.warnings.0.as_slice(),
                &[] as &[ncc::diagnostic::Diagnostic]
            );
        }
    }
    for release in [false, true] {
        for source in [
            "test \"type error\" { int value = true }",
            "fn identity<T>(T value) T { return value } test \"generic\" { _ = identity<int, bool>(1) }",
            "test \"embed\" { _ = @embed(\"missing-file\") }",
        ] {
            assert!(ncc::compile_test_source_with_options(source, path, release).is_err());
        }
        assert!(ncc::compile_source_with_options("test \"syntax\" {", path, release).is_err());
        assert!(ncc::compile_test_source_with_options("test \"syntax\" {", path, release).is_err());
    }
}

#[test]
fn imported_tests_are_filtered_before_module_qualification() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(
        directory.path().join("dependency.nc"),
        "pub fn value() int { return 7 }",
    )
    .unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "import { \"dependency\" as dep } pub fn value() int { return dep.value() } test \"private export\" { _ = dep.missing() }",
    ).unwrap();
    let source = "import { \"library\" as lib } @println(lib.value())";
    for release in [false, true] {
        ncc::compile_source_with_options(source, &path, release).unwrap();
        assert!(ncc::compile_test_source_with_options(source, &path, release).is_err());
    }
    fs::write(directory.path().join("library.nc"), "test \"syntax\" {").unwrap();
    assert!(ncc::compile_source(source, &path).is_err());
}

#[test]
fn test_dependency_slicing_preserves_transitive_mutations_and_order() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(
        directory.path().join("library.nc"),
        r#"
mut int shared = 0
pub fn change<T>(T ignored) { shared = shared + 1 }
pub fn read() int { return shared }
change<int>(0)
@println("unrelated imported output")
test "imported state" { assert shared == 1 }
"#,
    )
    .unwrap();
    for (source, expected) in [
        (
            r#"mut int value = 1 value = 2 int other_value = 5 @println(value, other_value) test "prior write" { assert value == 2 @println(value) } value = 9"#,
            "2\n",
        ),
        (
            r#"mut int value = 0 fn change() int { @print("needed:") value = 3 return 9 } int unused = change() int bad = true @println("unrelated") test "initializer writes" { assert value == 3 @println(value) }"#,
            "needed:3\n",
        ),
        (
            r#"mut int value = 0 fn change() { value = 4 } (fn() void) alias = change alias() test "alias" { assert value == 4 @println(value) }"#,
            "4\n",
        ),
        (
            r#"mut int value = 0 mut (fn() void) action = fn() {} action = fn() { value = 5 } action() test "replaced closure" { assert value == 5 @println(value) }"#,
            "5\n",
        ),
        (
            r#"mut int value = 0 { mut int value = 1 value = 8 @println("discard shadow") } test "shadow" { assert value == 0 @println(value) }"#,
            "0\n",
        ),
        (
            r#"mut int value = 0 fn change() { fn closure = fn() { value = 6 } closure() } change() test "nested closure" { assert value == 6 @println(value) }"#,
            "6\n",
        ),
        (
            r#"mut int value = 0 for i in [1, 2] { if i { 0 -> { value = 7 } _ -> {} } } test "nested write" { assert value == 7 @println(value) }"#,
            "7\n",
        ),
        (
            r#"mutex int value = 0 fn change() { lock value { value = 8 } } fut void work = async change() await work test "synchronized" { lock value { assert value == 8 @println(value) } }"#,
            "8\n",
        ),
        (
            r#"import { "library" as lib } lib.change<str>("ignored") @println("discard root output") test "generic imported mutation" { assert lib.read() == 2 @println(lib.read()) }"#,
            "2\n",
        ),
        (
            r#"fn make() (fn() int) { mut int cell = 0 return fn() int { cell = cell + 1 return cell } } (fn() int) counter = make() _ = counter() test "escaped captured state" { assert counter() == 2 @println(counter()) }"#,
            "3\n",
        ),
        (
            r#"mutex int value = 0 fn change() { lock value { value = 10 } } fut void work = async change() fn wait(fut void task) { await task } wait(work) test "indirect synchronization" { lock value { assert value == 10 @println(value) } }"#,
            "10\n",
        ),
    ] {
        fs::write(&path, source).unwrap();
        for mode in ["-d", "-r"] {
            let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
                .arg("test")
                .arg(&path)
                .arg(mode)
                .output()
                .unwrap();
            assert!(
                output.status.success(),
                "{source}, {mode}: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            assert_eq!(output.stdout, expected.as_bytes(), "{source}, {mode}");
        }
    }
    let source = r#"mut int value = 1 value = 2 int other_value = 5 @println(value, other_value) test "user example" { assert value == 1 }"#;
    fs::write(&path, source).unwrap();
    for mode in ["-d", "-r"] {
        let c = ncc::compile_test_source_with_options(source, &path, mode == "-r").unwrap();
        assert!(
            !c.contains("5LL"),
            "unrelated initializer was retained: {c}"
        );
        let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
            .arg("test")
            .arg(&path)
            .arg(mode)
            .output()
            .unwrap();
        assert!(!output.status.success());
        assert_eq!(output.stdout.as_slice(), b"");
        assert!(String::from_utf8_lossy(&output.stderr).contains("assert"));
    }
}

#[test]
fn isolated_tests_ignore_unused_errors_but_check_required_dependencies() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    let unused = r#"
import { "library" as lib }
extern "missing.c" as native { fn bad() int = "bad" }
fn bad() { _ = lib.missing() }
fn generic<T>(T value) T { return missing }
struct Bad { Missing field }
int invalid = true
_ = @embed("missing-file")
@println(missing)
"#;
    for release in [false, true] {
        for suffix in ["", "test \"isolated\" { assert lib.good() == 1 }"] {
            let source = format!("{unused}\n{suffix}");
            ncc::compile_test_source_with_options(&source, &path, release).unwrap();
        }
        for source in [
            "int invalid = true test \"required\" { _ = invalid }",
            "fn bad() int { return missing } test \"required\" { _ = bad() }",
            "import { \"library\" as lib } fn bad() { _ = lib.missing() } test \"required\" { bad() }",
            "extern \"missing.c\" as native { fn bad() int = \"bad\" } test \"required\" { _ = native.bad() }",
        ] {
            assert!(
                ncc::compile_test_source_with_options(source, &path, release).is_err(),
                "{source}"
            );
        }
    }
}

#[test]
fn test_slicing_retains_existing_binding_pattern_comparisons() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("patterns.nc");
    fs::write(
        &path,
        r#"
int expected = 2
mut int updated = 0
updated = 2
fn choose(int subject) int {
    return if subject { expected -> { 10 } _ -> { 20 } }
}
test "existing patterns" {
    int matched = if 1 { expected -> { 10 } _ -> { 20 } }
    assert matched == 20
    assert choose(1) == 20
    int changed = if 1 { updated -> { 10 } _ -> { 20 } }
    assert changed == 20
}
"#,
    )
    .unwrap();
    for mode in ["-d", "-r"] {
        let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
            .arg("test")
            .arg(&path)
            .arg(mode)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{mode}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn opaque_native_mutations_are_retained_without_nc_global_writes() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(directory.path().join("native.c"), "static int state; nc_abi_set_result set(void) { state = 9; } nc_abi_read_result read(void) { return state; }").unwrap();
    fs::write(
        &path,
        r#"
extern "native.c" as native { fn set() = "set" fn read() int = "read" }
native.set()
@println("discard")
test "native state" { assert native.read() == 9 @println(native.read()) }
"#,
    )
    .unwrap();
    for mode in ["-d", "-r"] {
        let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
            .arg("test")
            .arg(&path)
            .arg(mode)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(output.stdout, b"9\n");
    }
}

enum SlicingCliExpectation {
    Output,
    Diagnostic,
}

fn assert_slicing_cli_cases(
    directory: &Path,
    cases: &[(&str, &str)],
    expectation: &SlicingCliExpectation,
) {
    let path = directory.join("main.nc");
    let mut failures = Vec::new();
    for (source, expected) in cases {
        fs::write(&path, source).unwrap();
        for mode in ["-d", "-r"] {
            let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
                .arg("test")
                .arg(&path)
                .arg(mode)
                .output()
                .unwrap();
            let stderr = String::from_utf8_lossy(&output.stderr);
            let matches = match expectation {
                SlicingCliExpectation::Output => {
                    output.status.success() && output.stdout == expected.as_bytes()
                }
                SlicingCliExpectation::Diagnostic => {
                    !output.status.success()
                        && output.stdout.is_empty()
                        && stderr.contains(expected)
                }
            };
            if !matches {
                failures.push(format!(
                    "{mode}, expected {expected:?}: {source}\nstatus: {}\nstdout: {:?}\nstderr: {stderr}",
                    output.status,
                    String::from_utf8_lossy(&output.stdout),
                ));
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}

#[test]
fn test_slicing_direct_return_excludes_dead_writes_and_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn dead() int { return 7 value = 9 }
@println("excluded:", dead())
fn required() { @print("required:") value = 3 }
required()
test "live mutation" { assert value == 3 @println(value) }
"#,
                "required:3\n",
            ),
            (
                r#"
mut int value = 0
fn change() { value = 9 }
fn dead() int { return 7 change() }
@println("excluded:", dead())
test "dead transitive call" { assert value == 0 @println(value) }
"#,
                "0\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_direct_throw_break_continue_exclude_dead_effects() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut cases = Vec::new();
    for body in [
        r#"fn dead() int! { throw "must not execute" DEAD }"#,
        "fn dead() int { for i in [0] { break\nDEAD } return 7 }",
        "fn dead() int { for i in [0] { continue DEAD } return 7 }",
    ] {
        for effect in ["value = 9", "change()"] {
            cases.push(format!(
                r#"
mut int value = 0
fn change() {{ value = 9 }}
{}
@println("excluded:", dead())
test "dead effect" {{ assert value == 0 @println(value) }}
"#,
                body.replace("DEAD", effect),
            ));
        }
    }
    let cases: Vec<_> = cases
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_direct_return_excludes_dead_captured_writes() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make() (fn() int) {
    mut int cell = 0
    return fn() int { return cell cell = cell + 1 }
}
(fn() int) counter = make()
@println("excluded:", counter())
test "dead captured write" { assert counter() == 0 @println(counter()) }
"#,
            "0\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_direct_return_excludes_dead_await() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn produce() int { @println("worker") return 9 }
fut int work = async produce()
fn dead(fut int task) int { return 7 _ = await task }
@println("excluded:", dead(work))
test "live await" { assert await work == 9 @println("kept") }
"#,
            "worker\nkept\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_direct_return_excludes_dead_dynamic_and_native_opacity() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(directory.path().join("native.c"), "static int state; nc_abi_set_result set(void) { state = 9; } nc_abi_read_result read(void) { return state; }").unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn dead((fn() void) action) int { return 7 action() }
@println("excluded:", dead(fn() {}))
test "dead dynamic call" { assert value == 0 @println(value) }
"#,
                "0\n",
            ),
            (
                r#"
extern "native.c" as native { fn set() = "set" fn read() int = "read" }
fn dead() int { return 7 native.set() }
@println("excluded:", dead())
native.set()
test "live native mutation" { assert native.read() == 9 @println(native.read()) }
"#,
                "9\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_live_dynamic_calls_remain_conservative() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn invoke((fn() void) action) int { action() return 7 }
@println("required:", invoke(fn() { value = 1 }))
test "live dynamic call" { assert value == 1 @println(value) }
"#,
            "required:7\n1\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_jump_operands_retain_mutations() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn change() int { value = 1 return 7 }
fn result() int { return change() }
@println("required:", result())
test "return operand" { assert value == 1 @println(value) }
"#,
                "required:7\n1\n",
            ),
            (
                r#"
mut int value = 0
fn message() str { @print("required:") value = 1 return "failure" }
fn fail() void! { throw message() }
_ = fail()
test "throw operand" { assert value == 1 @println(value) }
"#,
                "required:1\n",
            ),
            (
                r#"
mut int value = 0
fn change() int { value = 1 return 7 }
int unused = if true { true -> { break change() } _ -> { 0 } }
test "value break operand" { assert value == 1 @println(value) }
"#,
                "1\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_scope_restoration_retains_reachable_mutations() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut cases = Vec::new();
    for body in [
        "if false { true -> { return 0 value = 9 } _ -> {} }",
        "while false { return 0 value = 9 }",
        "_ = false and change()",
        "_ = true or change()",
        "for i in [0] { { break } value = 9 }",
        "for i in [0] { { continue } value = 9 }",
    ] {
        cases.push(format!(
            r#"
mut int value = 0
fn change() bool {{ value = 9 return true }}
fn required() int {{
    {body}
    value = value + 1
    return 7
}}
@println("required:", required())
test "reachable mutation" {{ assert value == 1 @println(value) }}
"#,
        ));
    }
    let cases: Vec<_> = cases
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_retained_dead_code_keeps_struct_and_helper_dependencies() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
struct Box { int value }
fn helper() int { return 9 }
fn retained() int {
    return 7
    Box box = Box { .value = helper() }
    _ = box.value
}
test "syntax dependencies" { assert retained() == 7 @println(retained()) }
"#,
            "7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_retained_dead_code_still_rejects_semantic_errors() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"fn retained() int { return 7 int invalid = true } test "dead invalid" { assert retained() == 7 }"#,
                "expected `int`, found `bool`",
            ),
            (
                r#"fn helper() int { return missing } fn retained() int { return 7 _ = helper() } test "dead helper" { assert retained() == 7 }"#,
                "missing",
            ),
            (
                r#"struct Box { Missing field } fn retained() int { return 7 Box box = Box { .field = 0 } } test "dead type" { assert retained() == 7 }"#,
                "Missing",
            ),
            (
                r#"fn retained() int { int value = 0 return 7 value = 1 } test "dead assignment" { assert retained() == 7 }"#,
                "cannot mutate immutable",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_dead_assignments_preserve_qualification_error_evidence() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                "import { \"library\" as lib } for i in [0] { break\nlib.missing = 1 } test \"qualification\" { assert true }",
                "does not export `missing`",
            ),
            (
                r#"import { "library" as lib } for i in [0] { continue lib.missing = 1 } test "qualification" { assert true }"#,
                "does not export `missing`",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_boolean_dead_branches_exclude_writes_and_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut sources = Vec::new();
    for body in [
        "if false { true -> { EFFECT } false -> {} }",
        "if not false { false -> { EFFECT } true -> {} }",
        "if true and not false { false -> { EFFECT } _ -> {} }",
        "if false or true { false -> { EFFECT } _ -> {} }",
        "if { false -> { EFFECT } _ -> {} }",
        "if true { false, false -> { EFFECT } false, true -> {} _ -> { EFFECT } }",
        "if false { true, false -> {} _ -> { EFFECT } }",
        "if true { _ -> {} true -> { EFFECT } }",
        "while false { EFFECT }",
        "while not (true or false) { EFFECT }",
        "while false and change() { EFFECT }",
        "if false and change() { true -> { EFFECT } _ -> {} }",
        "if true or change() { false -> { EFFECT } _ -> {} }",
        "if { not true -> { EFFECT } _ -> {} }",
    ] {
        for effect in ["value = 9", "_ = change()"] {
            sources.push(format!(
                r#"
mut int value = 0
fn change() bool {{ value = 9 return true }}
fn dead() int {{ {} return 7 }}
@println("excluded:", dead())
test "dead Boolean effects" {{ assert value == 0 @println(value) }}
"#,
                body.replace("EFFECT", effect),
            ));
        }
    }
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_short_circuits_exclude_rhs_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "false and change()",
        "not true and change()",
        "(true and false) and change()",
        "true or change()",
        "not false or change()",
        "(false or true) or change()",
        "false and (true or change())",
        "true or (false and change())",
    ]
    .iter()
    .map(|expression| {
        format!(
            r#"
mut int value = 0
fn change() bool {{ value = 9 return true }}
fn dead() bool {{ return {expression} }}
@println("excluded:", dead())
test "dead RHS" {{ assert value == 0 @println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_dynamic_calls_exclude_opacity() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if false { true -> { _ = action() } _ -> {} }",
        "if { true -> {} _ -> { _ = action() } }",
        "while false { _ = action() }",
        "_ = false and action()",
        "_ = true or action()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
fn dead((fn() bool) action) int {{ {body} return 7 }}
@println("excluded:", dead(fn() bool {{ return true }}))
test "dead dynamic mutation" {{ assert value == 0 @println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_native_calls_exclude_opacity() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(directory.path().join("native.c"), "static int state; nc_abi_set_result set(void) { state = 9; } nc_abi_read_result read(void) { return state; }").unwrap();
    let sources: Vec<_> = [
        "if false { true -> { native.set() } _ -> {} }",
        "if { true -> {} _ -> { native.set() } }",
        "while false { native.set() }",
        "_ = false and mutate()",
        "_ = true or mutate()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
extern "native.c" as native {{ fn set() = "set" fn read() int = "read" }}
fn mutate() bool {{ native.set() return true }}
fn dead() int {{ {body} return 7 }}
@println("excluded:", dead())
native.set()
test "live native mutation" {{ assert native.read() == 9 @println(native.read()) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "9\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_await_does_not_retain_unrelated_output() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if false { true -> { _ = await task } _ -> {} }",
        "if { true -> {} _ -> { _ = await task } }",
        "while false { _ = await task }",
        "_ = false and await task",
        "_ = true or await task",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
fn produce() bool {{ @println("worker") return true }}
fut bool work = async produce()
fn dead(fut bool task) int {{ {body} return 7 }}
@println("excluded:", dead(work))
test "live await" {{ assert await work @println("kept") }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "worker\nkept\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_ordered_patterns_stop_dead_comparisons_and_arms() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { false, true, change() -> {} _ -> { _ = change() } }",
        "if false { true, false, change() -> {} _ -> { _ = change() } }",
        "if { false, true, change() -> {} _ -> { _ = change() } }",
        "if true { true -> {} change() -> {} _ -> { _ = change() } }",
        "if true { unknown() -> {} true -> {} change() -> {} _ -> { _ = change() } }",
        "if { unknown() -> {} false, true -> {} change() -> {} _ -> { _ = change() } }",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
fn unknown() bool {{ return false }}
fn change() bool {{ value = 9 return true }}
fn dead() int {{ {body} return 7 }}
@println("excluded:", dead())
test "ordered dead effects" {{ assert value == 0 @println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_reached_mutations_and_pattern_effects_are_retained() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { false -> {} true -> { value = value + 1 } }",
        "if not true { true -> {} _ -> { _ = change() } }",
        "if { false -> {} true -> { _ = change() } _ -> {} }",
        "if true { false, true -> { _ = change() } _ -> {} }",
        "_ = true and change()",
        "_ = false or change()",
        "_ = change() and false",
        "_ = change() or true",
        "while change() { break }",
        "if change() { true -> {} _ -> {} }",
        "if true { probe() -> {} true -> {} _ -> {} }",
        "if true { false, probe(), true -> {} _ -> {} }",
        "if { probe() -> {} false, true -> {} _ -> {} }",
        "if { probe(), true -> {} _ -> {} }",
        "if { change() -> {} _ -> {} }",
        "if true { expected -> {} true -> { _ = change() } _ -> {} }",
        "if false { expected -> { _ = change() } _ -> {} }",
        "if unknown { true -> { _ = change() } false -> {} }",
        "_ = unknown and change()",
        "_ = expected or change()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
bool expected = false
bool unknown = true
fn change() bool {{ value = value + 1 return true }}
fn probe() bool {{ value = value + 1 return false }}
fn required() int {{ {body} return 7 }}
@println("required:", required())
test "reached Boolean effects" {{ assert value == 1 @println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_reached_dynamic_mutations_are_retained() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { true -> { _ = action() } _ -> {} }",
        "if { action() -> {} _ -> {} }",
        "while action() { break }",
        "_ = true and action()",
        "_ = false or action()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
fn required((fn() bool) action) int {{ {body} return 7 }}
@println("required:", required(fn() bool {{ value = 1 return true }}))
test "reached dynamic mutation" {{ assert value == 1 @println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_syntax_keeps_type_and_value_dependencies() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
struct Box { int value }
mut int target = 0
fn helper() int { return 9 }
fn condition() bool { return true }
fn retained() int {
    if false { true -> { Box box = Box { .value = helper() } target = box.value } _ -> {} }
    while false { Box box = Box { .value = helper() } _ = box.value }
    _ = false and condition()
    _ = true or condition()
    if { true -> {} condition() -> { _ = helper() } _ -> {} }
    return 7
}
test "dead syntax dependencies" { assert retained() == 7 assert target == 0 @println(retained()) }
"#,
            "7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_boolean_dead_references_still_receive_semantic_checks() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"fn retained() { if false { true -> { int invalid = true } _ -> {} } } test "dead type" { retained() }"#,
                "expected `int`, found `bool`",
            ),
            (
                r#"fn helper() bool { return missing } fn retained() { _ = false and helper() } test "dead helper" { retained() }"#,
                "missing",
            ),
            (
                r#"fn helper() bool { return missing } fn retained() { _ = true or helper() } test "dead helper" { retained() }"#,
                "missing",
            ),
            (
                r#"struct Box { Missing field } fn retained() { while false { Box box = Box { .field = 0 } } } test "dead type" { retained() }"#,
                "Missing",
            ),
            (
                r#"int value = 0 fn retained() { if { true -> {} _ -> { value = 1 } } } test "dead assignment" { retained() }"#,
                "cannot mutate immutable",
            ),
            (
                r#"fn helper() bool { return missing } fn retained() { if true { false, true, helper() -> {} _ -> {} } } test "dead pattern" { retained() }"#,
                "missing",
            ),
            (
                r#"fn helper() bool { return missing } fn retained() { if { true -> {} helper() -> {} _ -> {} } } test "dead arm" { retained() }"#,
                "missing",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_boolean_dead_assignments_keep_qualification_evidence() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    let sources: Vec<_> = [
        "if false { true -> { lib.missing = 1 } _ -> {} }",
        "if { true -> {} _ -> { lib.missing = 1 } }",
        "while false { lib.missing = 1 }",
    ]
    .iter()
    .map(|body| {
        format!("import {{ \"library\" as lib }} {body} test \"qualification\" {{ assert true }}")
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "does not export `missing`"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Diagnostic);
}
