use std::{fs, path::Path, process::Command};

#[test]
fn compiles_and_runs_functions_conditionals_and_output() {
    let source = r#"
        fn classify(int value) int {
          if value {
            0 -> { return 10 }
            _ -> { return 20 }
          }
        }
        test "conditional" {
          assert classify(0) == 10
          assert classify(9) == 20
          @println(classify(0))
        }
    "#;
    let c = ncc::compile_test_source(source, std::path::Path::new("test.nc")).unwrap();
    let directory = std::env::temp_dir().join(format!("ncc-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source_path = directory.join("program.c");
    let executable = directory.join("program");
    fs::write(&source_path, c).unwrap();
    assert!(
        Command::new("cc")
            .arg(&source_path)
            .arg("-o")
            .arg(&executable)
            .status()
            .unwrap()
            .success()
    );
    let output = Command::new(&executable).output().unwrap();
    assert!(output.status.success());
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "10\n");
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn rejects_immutable_assignment() {
    let source = "test \"immutable\" { int value = 1;value = 2 }";
    let error = ncc::compile_test_source(source, std::path::Path::new("test.nc")).unwrap_err();
    assert!(error.to_string().contains("cannot mutate immutable"));
}

#[test]
fn allows_top_level_builtin_calls() {
    let source = "@print(\"Hello world\")";
    ncc::compile_source(source, std::path::Path::new("hello-world.nc")).unwrap();
    let c = ncc::compile_source(source, std::path::Path::new("hello-world.nc")).unwrap();
    assert!(c.contains("fwrite(") && c.contains(", stdout)"));
    assert!(c.contains("\"Hello world\""));
}

#[test]
fn run_does_not_leave_generated_files() {
    let directory = std::env::temp_dir().join(format!("ncc-run-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source = directory.join("hello.nc");
    fs::write(&source, "@print(\"hello\")").unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
        .arg("run")
        .arg(&source)
        .output()
        .unwrap();
    assert!(output.status.success());
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "hello");
    assert!(!directory.join("hello").exists());
    assert!(!directory.join("hello.c").exists());
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn build_only_leaves_the_requested_output() {
    let directory = std::env::temp_dir().join(format!("ncc-build-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source = directory.join("hello.nc");
    let executable = directory.join("greeting");
    fs::write(&source, "@print(\"hello\")").unwrap();
    let status = Command::new(env!("CARGO_BIN_EXE_ncc"))
        .args([
            "build",
            source.to_str().unwrap(),
            "--output",
            executable.to_str().unwrap(),
        ])
        .status()
        .unwrap();
    assert!(status.success());
    assert!(executable.exists());
    assert!(!directory.join("greeting.c").exists());
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn build_format_flag_overrides_the_output_extension() {
    let directory = std::env::temp_dir().join(format!("ncc-format-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source = directory.join("hello.nc");
    fs::write(&source, "@print(\"hello\")").unwrap();
    let c_output = directory.join("generated-without-extension");
    let object_output = directory.join("generated-object");
    let compiler = env!("CARGO_BIN_EXE_ncc");
    assert!(
        Command::new(compiler)
            .args([
                "build",
                source.to_str().unwrap(),
                "--format",
                "C",
                "--output",
                c_output.to_str().unwrap()
            ])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        fs::read_to_string(&c_output)
            .unwrap()
            .contains("Generated by ncc")
    );
    assert!(
        Command::new(compiler)
            .args([
                "build",
                source.to_str().unwrap(),
                "-f",
                "obj",
                "-o",
                object_output.to_str().unwrap()
            ])
            .status()
            .unwrap()
            .success()
    );
    assert!(fs::metadata(&object_output).unwrap().len() > 0);
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn supports_multiple_conditional_patterns() {
    let source = r"
        fn fibonacci(int n) int {
          if n {
            0, 1 -> { return n }
            _ -> { return fibonacci(n - 1) + fibonacci(n - 2) }
          }
        }
        @println(fibonacci(10))
    ";
    let directory = std::env::temp_dir().join(format!("ncc-fibonacci-test-{}", std::process::id()));
    let _ = fs::create_dir_all(&directory);
    let source_path = directory.join("fibonacci.nc");
    fs::write(&source_path, source).unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
        .arg("run")
        .arg(&source_path)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "55\n");
    let _ = fs::remove_dir_all(directory);
}

#[test]
fn explains_missing_conditional_arrow() {
    let source = "test \"bad conditional\" { if 1 { 1 { } } }";
    let error = ncc::compile_source(source, std::path::Path::new("bad.nc")).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("expected `->` after conditional pattern(s)")
    );
}

#[test]
fn emits_only_headers_required_by_the_program() {
    let no_headers = ncc::compile_source("fn noop() {}", std::path::Path::new("empty.nc")).unwrap();
    assert!(!no_headers.contains("#include"));

    let print_only =
        ncc::compile_source("@println(\"hello\")", std::path::Path::new("print.nc")).unwrap();
    assert!(print_only.contains("#include <stdio.h>"));
    assert!(!print_only.contains("#include <stdint.h>"));
    assert!(!print_only.contains("#include <stdbool.h>"));
    assert!(!print_only.contains("#include <stdlib.h>"));
    assert!(!print_only.contains("#include <math.h>"));
}

#[test]
fn ordinary_compilation_ignores_tests_before_semantic_processing() {
    let path = std::path::Path::new("ignored.nc");
    for source in [
        "test \"unknown\" { @println(missing) }",
        "test \"type error\" { int value = true }",
        "fn identity<T>(T value) T { return value };test \"generic\" { _ = identity<int, bool>(1) }",
        "test \"embed\" { _ = @embed(\"missing-file\") }",
        "test \"assert\" { assert false }",
        "test \"throw\" { throw \"failure\" }",
    ] {
        ncc::compile_source(source, path).unwrap();
        for release in [false, true] {
            let c = ncc::compile_source_with_options(source, path, release).unwrap();
            assert!(!c.contains("#include"), "{source}");
            let output = ncc::compile_source_with_diagnostics(source, path, release).unwrap();
            assert_eq!(
                output.warnings.0.as_slice(),
                &[] as &[ncc::diagnostic::Diagnostic]
            );
        }
    }
    for release in [false, true] {
        for source in [
            "test \"type error\" { int value = true }",
            "fn identity<T>(T value) T { return value };test \"generic\" { _ = identity<int, bool>(1) }",
            "test \"embed\" { _ = @embed(\"missing-file\") }",
        ] {
            assert!(ncc::compile_test_source_with_options(source, path, release).is_err());
        }
        assert!(ncc::compile_source_with_options("test \"syntax\" {", path, release).is_err());
        assert!(ncc::compile_test_source_with_options("test \"syntax\" {", path, release).is_err());
    }
}

#[test]
fn imported_tests_are_filtered_before_module_qualification() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(
        directory.path().join("dependency.nc"),
        "pub fn value() int { return 7 }",
    )
    .unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "import { \"dependency\" as dep };pub fn value() int { return dep.value() };test \"private export\" { _ = dep.missing() }",
    ).unwrap();
    let source = "import { \"library\" as lib };@println(lib.value())";
    for release in [false, true] {
        ncc::compile_source_with_options(source, &path, release).unwrap();
        assert!(ncc::compile_test_source_with_options(source, &path, release).is_err());
    }
    fs::write(directory.path().join("library.nc"), "test \"syntax\" {").unwrap();
    assert!(ncc::compile_source(source, &path).is_err());
}

#[test]
fn test_dependency_slicing_preserves_transitive_mutations_and_order() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(
        directory.path().join("library.nc"),
        r#"
mut int shared = 0
pub fn change<T>(T ignored) { shared = shared + 1 }
pub fn read() int { return shared }
change<int>(0)
@println("unrelated imported output")
test "imported state" { assert shared == 1 }
"#,
    )
    .unwrap();
    for (source, expected) in [
        (
            r#"mut int value = 1;value = 2;int other_value = 5;@println(value, other_value);test "prior write" { assert value == 2;@println(value) };value = 9"#,
            "2\n",
        ),
        (
            r#"mut int value = 0;fn change() int { @print("needed:");value = 3;return 9 };int unused = change();int bad = true;@println("unrelated");test "initializer writes" { assert value == 3;@println(value) }"#,
            "needed:3\n",
        ),
        (
            r#"mut int value = 0;fn change() { value = 4 };(fn() void) alias = change;alias();test "alias" { assert value == 4;@println(value) }"#,
            "4\n",
        ),
        (
            r#"mut int value = 0;mut (fn() void) action = fn() {};action = fn() { value = 5 };action();test "replaced closure" { assert value == 5;@println(value) }"#,
            "5\n",
        ),
        (
            r#"mut int value = 0;{ mut int value = 1;value = 8;@println("discard shadow") };test "shadow" { assert value == 0;@println(value) }"#,
            "0\n",
        ),
        (
            r#"mut int value = 0;fn change() { fn closure = fn() { value = 6 };closure() };change();test "nested closure" { assert value == 6;@println(value) }"#,
            "6\n",
        ),
        (
            r#"mut int value = 0;for i in [1, 2] { if i { 0 -> { value = 7 } _ -> {} } };test "nested write" { assert value == 7;@println(value) }"#,
            "7\n",
        ),
        (
            r#"mutex int value = 0;fn change() { lock value { value = 8 } };fut void work = async change();await work;test "synchronized" { lock value { assert value == 8;@println(value) } }"#,
            "8\n",
        ),
        (
            r#"import { "library" as lib };lib.change<str>("ignored");@println("discard root output");test "generic imported mutation" { assert lib.read() == 2;@println(lib.read()) }"#,
            "2\n",
        ),
        (
            r#"fn make() (fn() int) { mut int cell = 0;return fn() int { cell = cell + 1;return cell } };(fn() int) counter = make();_ = counter();test "escaped captured state" { assert counter() == 2;@println(counter()) }"#,
            "3\n",
        ),
        (
            r#"mutex int value = 0;fn change() { lock value { value = 10 } };fut void work = async change();fn wait(fut void task) { await task };wait(work);test "indirect synchronization" { lock value { assert value == 10;@println(value) } }"#,
            "10\n",
        ),
    ] {
        fs::write(&path, source).unwrap();
        for mode in ["-d", "-r"] {
            let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
                .arg("test")
                .arg(&path)
                .arg(mode)
                .output()
                .unwrap();
            assert!(
                output.status.success(),
                "{source}, {mode}: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            assert_eq!(output.stdout, expected.as_bytes(), "{source}, {mode}");
        }
    }
    let source = r#"mut int value = 1;value = 2;int other_value = 5;@println(value, other_value);test "user example" { assert value == 1 }"#;
    fs::write(&path, source).unwrap();
    for mode in ["-d", "-r"] {
        let c = ncc::compile_test_source_with_options(source, &path, mode == "-r").unwrap();
        assert!(
            !c.contains("5LL"),
            "unrelated initializer was retained: {c}"
        );
        let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
            .arg("test")
            .arg(&path)
            .arg(mode)
            .output()
            .unwrap();
        assert!(!output.status.success());
        assert_eq!(output.stdout.as_slice(), b"");
        assert!(String::from_utf8_lossy(&output.stderr).contains("assert"));
    }
}

#[test]
fn isolated_tests_ignore_unused_errors_but_check_required_dependencies() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    let unused = r#"
import { "library" as lib }
extern "missing.c" as native { fn bad() int = "bad" }
fn bad() { _ = lib.missing() }
fn generic<T>(T value) T { return missing }
struct Bad { Missing field }
int invalid = true
_ = @embed("missing-file")
@println(missing)
"#;
    for release in [false, true] {
        for suffix in ["", "test \"isolated\" { assert lib.good() == 1 }"] {
            let source = format!("{unused}\n{suffix}");
            ncc::compile_test_source_with_options(&source, &path, release).unwrap();
        }
        for source in [
            "int invalid = true;test \"required\" { _ = invalid }",
            "fn bad() int { return missing };test \"required\" { _ = bad() }",
            "import { \"library\" as lib };fn bad() { _ = lib.missing() };test \"required\" { bad() }",
            "extern \"missing.c\" as native { fn bad() int = \"bad\" };test \"required\" { _ = native.bad() }",
        ] {
            assert!(
                ncc::compile_test_source_with_options(source, &path, release).is_err(),
                "{source}"
            );
        }
    }
}

#[test]
fn test_slicing_retains_existing_binding_pattern_comparisons() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("patterns.nc");
    fs::write(
        &path,
        r#"
int expected = 2
mut int updated = 0
updated = 2
fn choose(int subject) int {
    return if subject { expected -> { 10 } _ -> { 20 } }
}
test "existing patterns" {
    int matched = if 1 { expected -> { 10 } _ -> { 20 } }
    assert matched == 20
    assert choose(1) == 20
    int changed = if 1 { updated -> { 10 } _ -> { 20 } }
    assert changed == 20
}
"#,
    )
    .unwrap();
    for mode in ["-d", "-r"] {
        let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
            .arg("test")
            .arg(&path)
            .arg(mode)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{mode}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn opaque_native_mutations_are_retained_without_nc_global_writes() {
    let directory = ncc::temp::Directory::new().unwrap();
    let path = directory.path().join("main.nc");
    fs::write(directory.path().join("native.c"), "static int state; nc_abi_set_result set(void) { state = 9; } nc_abi_read_result read(void) { return state; }").unwrap();
    fs::write(
        &path,
        r#"
extern "native.c" as native { fn set() = "set" fn read() int = "read" }
native.set()
@println("discard")
test "native state" { assert native.read() == 9;@println(native.read()) }
"#,
    )
    .unwrap();
    for mode in ["-d", "-r"] {
        let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
            .arg("test")
            .arg(&path)
            .arg(mode)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(output.stdout, b"9\n");
    }
}

enum SlicingCliExpectation {
    Output,
    Diagnostic,
}

fn assert_slicing_cli_cases(
    directory: &Path,
    cases: &[(&str, &str)],
    expectation: &SlicingCliExpectation,
) {
    let path = directory.join("main.nc");
    let mut failures = Vec::new();
    for (source, expected) in cases {
        fs::write(&path, source).unwrap();
        for mode in ["-d", "-r"] {
            let output = Command::new(env!("CARGO_BIN_EXE_ncc"))
                .arg("test")
                .arg(&path)
                .arg(mode)
                .output()
                .unwrap();
            let stderr = String::from_utf8_lossy(&output.stderr);
            let matches = match expectation {
                SlicingCliExpectation::Output => {
                    output.status.success() && output.stdout == expected.as_bytes()
                }
                SlicingCliExpectation::Diagnostic => {
                    !output.status.success()
                        && output.stdout.is_empty()
                        && stderr.contains(expected)
                }
            };
            if !matches {
                failures.push(format!(
                    "{mode}, expected {expected:?}: {source}\nstatus: {}\nstdout: {:?}\nstderr: {stderr}",
                    output.status,
                    String::from_utf8_lossy(&output.stdout),
                ));
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}

#[test]
fn test_slicing_unused_lambda_discards_callback_only_writes_and_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn ignore((fn() void) callback) { @println("discarded call") }
ignore(fn() void { value = 9 })
test "unused direct write" { assert value == 0;@println(value) }
"#,
                "0\n",
            ),
            (
                r#"
mut int value = 0
fn change() { value = 9 }
fn ignore((fn() void) callback) { @println("discarded call") }
ignore(fn() void { change() })
test "unused helper call" { assert value == 0;@println(value) }
"#,
                "0\n",
            ),
            (
                r#"
mut int value = 0
fn change() { value = 9 }
fn ignore((fn() void) callback) { @println("discarded call") }
ignore(fn() void { fut void work = async change();await work })
test "unused async callback" { assert value == 0;@println(value) }
"#,
                "0\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_does_not_promote_dynamic_or_recursive_effects() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "(fn() void) indirect = action;indirect()",
        "recurse(2)",
        "fut void work = async recurse(2);await work",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int observed = 0
mut int unrelated = 0
fn action() {{ unrelated = unrelated + 1;@println("discarded invocation:", unrelated) }}
action()
fn recurse(int n) {{
    if n > 0 {{ true -> {{ recurse(n - 1) }} _ -> {{ action() }} }}
}}
fn retain((fn() void) callback) {{ observed = 7;@println("retained call") }}
retain(fn() void {{ {body} }})
test "unused invocation effects" {{ assert observed == 7;@println(observed) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "retained call\n7\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_escaped_cell_proxy_discards_syntax_only_invocation_history() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make() (fn() int) {
    mut int cell = 0
    @println("action initializer")
    return fn() int { cell = cell + 1;@println("discarded action:", cell);return cell }
}
(fn() int) action = make()
_ = action()
fn answer() int { return 7;_ = action() }
test "syntax-only escaped callable" { assert answer() == 7;@println(answer()) }
"#,
            "action initializer\n7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_escaped_cell_proxy_separates_independent_factory_instances() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make(str name) (fn() int) {
    mut int cell = 0
    return fn() int { cell = cell + 1;@println(name, ":", cell);return cell }
}
(fn() int) first = make("first")
(fn() int) second = make("discarded second")
_ = second()
_ = first()
_ = second()
_ = first()
test "independent escaped cells" {
    int actual = first()
    assert actual == 3
    @println("observed:", actual)
}
"#,
            "first:1\nfirst:2\nfirst:3\nobserved:3\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_escaped_cell_proxy_preserves_factory_calls_to_global_counter() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make_counter() (fn() int) {
    mut int cell = 0
    return fn() int { cell = cell + 1;@println("counter:", cell);return cell }
}
(fn() int) counter = make_counter()
_ = counter()
fn make() (fn() int) {
    @println("factory before")
    _ = counter()
    @println("factory after")
    mut int own = 0
    return fn() int { own = own + 1;return own }
}
_ = make()
test "factory mutates existing escaped cell" {
    int actual = counter()
    assert actual == 3
    @println("observed:", actual)
}
"#,
            "counter:1\nfactory before\ncounter:2\nfactory after\ncounter:3\nobserved:3\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_escaped_cell_proxy_preserves_destructured_sibling_writer_history() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make() ((fn() void), (fn() int)) {
    mut int cell = 0
    return fn() void { cell = cell + 1;@println("writer:", cell) },
        fn() int { return cell }
}
(fn() void) writer, (fn() int) reader = make()
writer()
writer()
test "sibling escaped cell" { assert reader() == 2;@println("observed:", reader()) }
"#,
            "writer:1\nwriter:2\nobserved:2\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_escaped_cell_proxy_preserves_alias_and_replacement_histories() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make(str name) (fn() int) {
    mut int cell = 0
    return fn() int { cell = cell + 1;@println(name, ":", cell);return cell }
}
mut (fn() int) action = make("original")
(fn() int) alias = action
_ = action()
action = make("replacement")
_ = alias()
_ = action()
test "escaped alias survives replacement" {
    assert alias() == 3
    assert action() == 2
}
"#,
            "original:1\noriginal:2\nreplacement:1\noriginal:3\nreplacement:2\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_escaped_cell_proxy_preserves_async_mutex_sibling_history() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make() ((fn() void), (fn() int)) {
    mutex int cell = 0
    return fn() void { lock cell { cell = cell + 1;@println("writer:", cell) } },
        fn() int { lock cell { return cell } }
}
(fn() void) writer, (fn() int) reader = make()
writer()
fut void work = async writer()
{ await work;@println("waited") }
test "async sibling escaped mutex" { assert reader() == 2;@println("observed:", reader()) }
"#,
            "writer:1\nwriter:2\nwaited\nobserved:2\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_preserves_capture_initializers() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int observed = 0
fn initialize() int { @println("capture initializer");return 9 }
int captured = initialize()
fn retain((fn() int) callback) { observed = 7 }
retain(fn() int { return captured })
test "unused capture dependency" { assert observed == 7;@println(observed) }
"#,
            "capture initializer\n7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_preserves_prior_mutable_capture_mutations() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int captured = 0
mut int observed = 0
fn change() { captured = 9;@println("capture mutation:", captured) }
change()
fn retain((fn() int) callback) { observed = 7 }
retain(fn() int { return captured })
test "conservative mutable capture" { assert observed == 7;@println(observed) }
"#,
            "capture mutation:9\n7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_refinement_respects_callee_shadowing() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn ignore((fn() void) callback) {}
{
    (fn((fn() void)) void) ignore = fn((fn() void) callback) { callback() }
    ignore(fn() void { value = 9;@println("local callback") })
}
test "local callee shadow" { assert value == 9;@println(value) }
"#,
                "local callback\n9\n",
            ),
            (
                r#"
mut int value = 0
fn ignore((fn() void) callback) {}
fn invoke((fn() void) callback) { callback() }
fn caller((fn((fn() void)) void) ignore) {
    ignore(fn() void { value = 9;@println("parameter callback") })
}
caller(invoke)
test "parameter callee shadow" { assert value == 9;@println(value) }
"#,
                "parameter callback\n9\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_certification_checks_dead_parameter_references() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn accept((fn() void) callback) {
    return
    _ = callback == callback
}
accept(fn() void { value = 9 })
test "dead callback equality" { assert value == 0 }
"#,
            "equality is not defined",
        )],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_unused_lambda_certification_checks_name_pattern_parameters() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn accept((fn() void) callback) {
    if fn() void {} { callback -> {} _ -> {} }
}
accept(fn() void { value = 9 })
test "callback name pattern" { assert value == 0 }
"#,
            "pattern equality is not defined",
        )],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_unused_lambda_preserves_partial_qualification_assignment_fallback() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
import { "library" as lib }
mut int value = 0
fn ignore((fn() void) callback) {}
ignore(fn() void { _ = lib.good();_ = lib.missing();value = 9 })
test "partial callback qualification" { assert value == 0 }
"#,
            "does not export `missing`",
        )],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_unused_lambda_refinement_preserves_used_callbacks() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "fn accept((fn() void) callback) { callback() }\naccept(fn() void { value = 9 })",
        "fn accept((fn() void) callback) (fn() void) { return callback }\n(fn() void) action = accept(fn() void { value = 9 })\naction()",
        "fn invoke((fn() void) callback) { callback() }\nfn accept((fn() void) callback) { invoke(callback) }\naccept(fn() void { value = 9 })",
        "fn accept((fn() void) callback) (fn() void) { return fn() void { callback() } }\n(fn() void) action = accept(fn() void { value = 9 })\naction()",
        "fn accept((fn() void) callback) { return callback() }\naccept(fn() void { value = 9 })",
    ]
    .iter()
    .map(|call| {
        format!(
            r#"
mut int value = 0
{call}
test "used callback" {{ assert value == 9;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "9\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_unused_lambda_refinement_preserves_argument_evaluation() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn produce() (fn() void) { value = 9;@println("producer");return fn() void {} }
fn ignore((fn() void) callback) { @println("retained call") }
ignore(produce())
test "effectful callback producer" { assert value == 9;@println(value) }
"#,
                "producer\nretained call\n9\n",
            ),
            (
                r#"
mut int value = 0
fn produce() int { value = 9;@println("producer");return 1 }
fn ignore((fn() void) callback, int argument) { @println("retained call") }
ignore(fn() void {}, produce())
test "ordinary argument effect" { assert value == 9;@println(value) }
"#,
                "producer\nretained call\n9\n",
            ),
            (
                r#"
mut int value = 0
(fn() void { value = 9;@println("immediate lambda") })()
test "immediate invocation" { assert value == 9;@println(value) }
"#,
                "immediate lambda\n9\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_discards_irrelevant_local_diagnostics() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn ignore((fn() void) callback) { @println("discarded call") }
ignore(fn() void { value = 9;_ = missing })
test "irrelevant bad callback" { assert value == 0;@println(value) }
"#,
            "0\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_preserves_relevant_local_diagnostics() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn retain((fn() void) callback) { value = 7 }
retain(fn() void { _ = missing })
test "relevant bad callback" { assert value == 7 }
"#,
            "unknown name `missing`",
        )],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_unused_lambda_discards_irrelevant_imported_diagnostics() {
    let directory = ncc::temp::Directory::new().unwrap();
    let library = directory.path().join("library.nc");
    fs::write(&library, "\npub fn helper() int { return missing }\n").unwrap();

    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
import { "library" as lib }
mut int value = 0
fn ignore((fn() void) callback) { @println("discarded call") }
ignore(fn() void { value = lib.helper() })
test "irrelevant imported helper" { assert value == 0;@println(value) }
"#,
            "0\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_unused_lambda_preserves_relevant_imported_diagnostics() {
    let directory = ncc::temp::Directory::new().unwrap();
    let library = directory.path().join("library.nc");
    fs::write(&library, "\npub fn helper() int { return missing }\n").unwrap();
    let expected = format!("{}:2:30: error: unknown name `missing`", library.display());
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
import { "library" as lib }
mut int value = 0
fn retain((fn() int) callback) { value = 7 }
retain(fn() int { return lib.helper() })
test "relevant imported helper" { assert value == 7 }
"#,
            &expected,
        )],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_runtime_demand_excludes_mutations_for_dead_helper_references() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn mutate() { @println("discarded mutation");value = 9 }
mutate()
struct Box { int value }
fn helper() int { return value }
fn retained() int { return 7;Box box = Box { .value = helper() };_ = box.value }
test "dead direct reference" { assert retained() == 7;@println(retained()) }
"#,
                "7\n",
            ),
            (
                r#"
mut int value = 0
fn mutate() { @println("discarded mutation");value = 9 }
mutate()
fn helper(int n) int {
    if n > 0 { true -> { return helper(n - 1) } _ -> {} }
    return value
}
fn retained() int { return 7;_ = helper(2) }
test "dead recursive reference" { assert retained() == 7;@println(retained()) }
"#,
                "7\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_synchronization_excludes_waits_for_dead_helper_references() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mutex int value = 0
fn read() int { lock value { return value } }
fn produce() int { return 7;_ = read() }
fut int work = async produce()
@println("discarded wait:", await work)
test "dead declaration edge" { lock value { assert value == 0;@println(value) } }
"#,
                "0\n",
            ),
            (
                r#"
mutex int value = 0
fn read() int { lock value { return value } }
fn produce() int { return 7 }
fut int work = async produce()
fn wait(fut int task) int { return await task;_ = read() }
@println("discarded wait:", wait(work))
test "dead starting reference" { lock value { assert value == 0;@println(value) } }
"#,
                "0\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_synchronization_preserves_wait_for_native_mutex_reader() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(
        directory.path().join("native.c"),
        "nc_abi_invoke_result invoke(nc_abi_invoke_arg0 callback) { return callback.call(callback.env); }",
    )
    .unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
extern "native.c" as native { fn invoke((fn() int) callback) int = "invoke" }
mutex int value = 0
fn change() { lock value { value = 9 } }
fn read() int { lock value { return value } }
fut void work = async change()
fn wait(fut void task) { await task }
{ wait(work);@println("waited") }
test "native mutex reader" { @println("kept:", native.invoke(read)) }
"#,
            "waited\nkept:9\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_synchronization_preserves_wait_for_captured_mutex_state() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make() (fn() int) {
    mutex int cell = 0
    return fn() int { lock cell { cell = cell + 1;return cell } }
}
(fn() int) counter = make()
fn bump() { _ = counter() }
fut void work = async bump()
{ await work;@println("waited") }
fn read() int { return counter() }
test "escaped mutex state" { @println("kept:", read()) }
"#,
            "waited\nkept:2\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_runtime_demand_preserves_direct_and_mutual_recursive_reads() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
value = 5
fn read() int { return value }
test "direct read" { assert read() == 5;@println(read()) }
"#,
                "5\n",
            ),
            (
                r#"
mut int value = 0
value = 2
fn mutate() { @println("required mutation");value = value + 3 }
mutate()
fn first(int n) int {
    if n > 0 { true -> { return second(n - 1) } _ -> {} }
    return value
}
fn second(int n) int { return first(n) }
test "mutual recursive read" { assert first(3) == 5;@println(second(2)) }
"#,
                "required mutation\n5\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_callable_promotion_excludes_dead_references() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "(fn() int) action = fn() int { return 7;_ = read() }",
        "mut (fn() int) action = fn() int { return 0 }\naction = fn() int { return 7;_ = read() }",
        "(fn() int) original = fn() int { if false { true -> { _ = read() } _ -> {} };return 7 }\nmut (fn() int) action = fn() int { return 0 }\naction = original",
        "mut (fn() int) action = fn() int { return 0 }\naction = fn() int { _ = false and read() == 9;return 7 }",
    ]
    .iter()
    .map(|callable| {
        format!(
            r#"
mut int value = 0
fn mutate() {{ @println("discarded mutation");value = 9 }}
mutate()
fn read() int {{ return value }}
{callable}
test "dead callable reference" {{ assert action() == 7;@println(action()) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "7\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_callable_promotion_preserves_returned_and_captured_aliases() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn mutate() { @println("required mutation");value = 9 }
mutate()
fn first(int n) int {
    if n > 0 { true -> { return second(n - 1) } _ -> {} }
    return value
}
fn second(int n) int { return first(n) }
fn read() int { return first(3) }
fn make() (fn() int) { return read }
(fn() int) original = make()
mut (fn() int) action = fn() int { return 0 }
action = original
test "returned recursive callback" { assert action() == 9;@println(action()) }
"#,
                "required mutation\n9\n",
            ),
            (
                r#"
fn make() (fn() int) {
    mut int cell = 0
    return fn() int { cell = cell + 1;return cell }
}
(fn() int) counter = make()
mut (fn() int) action = fn() int { return 0 }
action = counter
@println("required prior:", action())
test "captured alias replacement" { @println("kept:", action()) }
"#,
                "required prior:1\nkept:2\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_callable_promotion_preserves_mutex_synchronization() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mutex int value = 0
fn change() { lock value { value = 9 } }
fut void work = async change()
{ await work;@println("waited") }
fn read() int { lock value { return value } }
fn make() (fn() int) { return read }
mut (fn() int) action = fn() int { return 0 }
action = make()
test "returned mutex reader" { assert action() == 9;@println(action()) }
"#,
                "waited\n9\n",
            ),
            (
                r#"
fn make() (fn() int) {
    mutex int cell = 0
    return fn() int { lock cell { cell = cell + 1;return cell } }
}
(fn() int) counter = make()
mut (fn() int) action = fn() int { return 0 }
action = counter
fn bump() { _ = action() }
fut void work = async bump()
{ await work;@println("waited") }
test "escaped mutex alias" { @println("kept:", action()) }
"#,
                "waited\nkept:2\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_callable_promotion_preserves_dead_imported_diagnostics() {
    let directory = ncc::temp::Directory::new().unwrap();
    let library = directory.path().join("library.nc");
    let expected = format!("{}:2:26: error: unknown name `missing`", library.display());
    for callable in [
        "(fn() int) action = fn() int { return 7;_ = helper() }",
        "mut (fn() int) action = fn() int { return 0 }\naction = fn() int { return 7;_ = helper() }",
    ] {
        fs::write(
            &library,
            format!(
                "\nfn helper() int {{ return missing }}\n{callable}\npub fn retained() int {{ return action() }}\n"
            ),
        )
        .unwrap();
        assert_slicing_cli_cases(
            directory.path(),
            &[(
                r#"import { "library" as lib };test "dead imported callable" { assert lib.retained() == 7 }"#,
                &expected,
            )],
            &SlicingCliExpectation::Diagnostic,
        );
    }
}

#[test]
fn test_slicing_runtime_demand_preserves_opaque_callback_state() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
value = 9
fn read() int { return value }
fn invoke((fn() int) action) int { return action() }
test "reader callback" { assert invoke(read) == 9;@println(invoke(read)) }
"#,
                "9\n",
            ),
            (
                r#"
mut int value = 0
value = 9
fn read() int { return value }
fn invoke() int { (fn() int) action = read;return action() }
test "local reader alias" { assert invoke() == 9;@println(invoke()) }
"#,
                "9\n",
            ),
            (
                r#"
mut int value = 0
value = 9
fn read() int { return value }
mut (fn() int) action = fn() int { return 0 }
action = read
fn invoke((fn() int) callback) int { return callback() }
test "replaced reader callback" { assert invoke(action) == 9;@println(invoke(action)) }
"#,
                "9\n",
            ),
            (
                r#"
fn make() (fn() int) {
    mut int cell = 0
    return fn() int { cell = cell + 1;return cell }
}
(fn() int) counter = make()
_ = counter()
fn read() int { return counter() }
fn invoke((fn() int) action) int { return action() }
test "escaped counter callback" { assert invoke(read) == 2;@println(invoke(read)) }
"#,
                "3\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_runtime_demand_preserves_syntax_selected_global_initializer() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn mutate() { @println("required mutation");value = 5 }
mutate()
fn initialize() int { @println("initializer:", value);return value }
int snapshot = initialize()
fn retained() int { return 7;_ = snapshot }
test "syntax selected initializer" { assert retained() == 7;@println(retained()) }
"#,
            "required mutation\ninitializer:5\n7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_runtime_demand_preserves_dead_dependency_diagnostic_locations() {
    let directory = ncc::temp::Directory::new().unwrap();
    let library = directory.path().join("library.nc");
    for (source, location, diagnostic) in [
        (
            "\nfn helper() int { return missing }\npub fn retained() int { return 7;_ = helper() }\n",
            "2:26",
            "unknown name `missing`",
        ),
        (
            "\nstruct Box { Missing field }\npub fn retained() int { return 7;Box box = Box { .field = 0 };_ = box.field }\n",
            "2:1",
            "unknown type `Missing`",
        ),
    ] {
        fs::write(&library, source).unwrap();
        let expected = format!("{}:{location}: error: {diagnostic}", library.display());
        assert_slicing_cli_cases(
            directory.path(),
            &[(
                r#"import { "library" as lib };test "dead imported dependency" { assert lib.retained() == 7 }"#,
                &expected,
            )],
            &SlicingCliExpectation::Diagnostic,
        );
    }
}

#[test]
fn test_slicing_direct_return_excludes_dead_writes_and_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn dead() int { return 7;value = 9 }
@println("excluded:", dead())
fn required() { @print("required:");value = 3 }
required()
test "live mutation" { assert value == 3;@println(value) }
"#,
                "required:3\n",
            ),
            (
                r#"
mut int value = 0
fn change() { value = 9 }
fn dead() int { return 7;change() }
@println("excluded:", dead())
test "dead transitive call" { assert value == 0;@println(value) }
"#,
                "0\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_direct_throw_break_continue_exclude_dead_effects() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut cases = Vec::new();
    for body in [
        r#"fn dead() int! { throw "must not execute";DEAD }"#,
        "fn dead() int { for i in [0] { break\nDEAD };return 7 }",
        "fn dead() int { for i in [0] { continue;DEAD };return 7 }",
    ] {
        for effect in ["value = 9", "change()"] {
            cases.push(format!(
                r#"
mut int value = 0
fn change() {{ value = 9 }}
{}
@println("excluded:", dead())
test "dead effect" {{ assert value == 0;@println(value) }}
"#,
                body.replace("DEAD", effect),
            ));
        }
    }
    let cases: Vec<_> = cases
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_plain_block_exits_exclude_enclosing_dead_effects() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut sources = Vec::new();
    for exit in ["return 7", r#"throw "must not execute""#] {
        for block in [
            "{ int local = 1;EXIT }",
            "{ int local = 1;{ _ = local;EXIT } }",
        ] {
            for effect in ["value = 9", "change()"] {
                sources.push(format!(
                    r#"
mut int value = 0
fn change() {{ value = 9 }}
fn dead() int! {{ {};{effect} }}
@println("excluded:", dead())
fn required() {{ @print("required:");value = value + 1 }}
required()
test "nested exit" {{ assert value == 1;@println(value) }}
"#,
                    block.replace("EXIT", exit),
                ));
            }
        }
    }
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_plain_block_loop_exits_keep_after_loop_effects() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut sources = Vec::new();
    for exit in ["break", "continue"] {
        for body in [
            "for i in [0, 1] { { _ = i;{ EXIT } };EFFECT }",
            "mut int i = 2;while i > 0 { i = i - 1;{ { EXIT } };EFFECT }",
        ] {
            for effect in ["value = 9", "change()"] {
                let body = body.replace("EXIT", exit).replace("EFFECT", effect);
                sources.push(format!(
                    r#"
mut int value = 0
fn change() {{ value = 9 }}
fn dead() int {{ {body};return 7 }}
@println("excluded:", dead())
fn required() int {{
    {body}
    @print("required:")
    value = value + 1
    return 7
}}
@println(required())
test "after loop" {{ assert value == 1;@println(value) }}
"#,
                ));
            }
        }
    }
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_plain_block_scope_boundaries_keep_reached_effects() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "done: if true { true -> { { break :done } } _ -> {} }",
        "done: lock guard { { { break :done } } }",
        "lock guard { { break } }",
        "int[] items = [];for i in items { { return 0 } }",
        "while false { { throw \"not reached\" } }",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
mutex int guard = 0
fn required() int! {{
    {{
        {body}
        @print("required:")
        value = value + 1
    }}
    return 7
}}
@println(required() catch err {{ throw err }})
test "scope continuation" {{ assert value == 1;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_plain_block_value_breaks_keep_expression_continuations() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { true -> { { { break 7 } };value = 9;change();0 } _ -> { 0 } }",
        "absent else { { { break 7 } };value = 9;change();0 }",
        "fail() catch err { { { break 7 } };value = 9;change();0 }",
    ]
    .iter()
    .map(|expression| {
        format!(
            r#"
mut int value = 0
int? absent = none
fn fail() int! {{ throw "fallback" }}
fn change() {{ value = 9 }}
fn dead() int {{ int result = {expression};return result }}
@println("excluded:", dead())
fn required() int {{
    {{
        int result = {expression}
        @print("required:")
        value = value + 1
        return result
    }}
}}
@println(required())
test "value block continuation" {{ assert value == 1;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_plain_block_dead_suffix_keeps_syntax_and_qualification() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
struct Box { int value }
fn helper() int { return 9 }
fn retained() int {
    { int local = 1;{ _ = local;return 7 } }
    Box box = Box { .value = helper() }
    _ = box.value
}
test "nested syntax dependencies" { assert retained() == 7;@println(retained()) }
"#,
            "7\n",
        )],
        &SlicingCliExpectation::Output,
    );
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"fn helper() int { return missing };fn retained() int { { { return 7 } };_ = helper() };test "dead helper" { assert retained() == 7 }"#,
                "missing",
            ),
            (
                r#"fn retained() int { { { return 7 } };int invalid = true };test "dead invalid" { assert retained() == 7 }"#,
                "expected `int`, found `bool`",
            ),
            (
                r#"import { "library" as lib };fn retained() int { { { return 7 } };lib.missing = 1 };test "qualification" { assert retained() == 7 }"#,
                "does not export `missing`",
            ),
            (
                "import { \"library\" as lib };for i in [0] { { { break } }\nlib.missing = 1 };test \"qualification\" { assert true }",
                "does not export `missing`",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_direct_return_excludes_dead_captured_writes() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn make() (fn() int) {
    mut int cell = 0
    return fn() int { return cell;cell = cell + 1 }
}
(fn() int) counter = make()
@println("excluded:", counter())
test "dead captured write" { assert counter() == 0;@println(counter()) }
"#,
            "0\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_direct_return_excludes_dead_await() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
fn produce() int { @println("worker");return 9 }
fut int work = async produce()
fn dead(fut int task) int { return 7;_ = await task }
@println("excluded:", dead(work))
test "live await" { assert await work == 9;@println("kept") }
"#,
            "worker\nkept\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_direct_return_excludes_dead_dynamic_and_native_opacity() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(directory.path().join("native.c"), "static int state; nc_abi_set_result set(void) { state = 9; } nc_abi_read_result read(void) { return state; }").unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn dead((fn() void) action) int { return 7;action() }
@println("excluded:", dead(fn() {}))
test "dead dynamic call" { assert value == 0;@println(value) }
"#,
                "0\n",
            ),
            (
                r#"
extern "native.c" as native { fn set() = "set" fn read() int = "read" }
fn dead() int { return 7;native.set() }
@println("excluded:", dead())
native.set()
test "live native mutation" { assert native.read() == 9;@println(native.read()) }
"#,
                "9\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_live_dynamic_calls_remain_conservative() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
mut int value = 0
fn invoke((fn() void) action) int { action();return 7 }
@println("required:", invoke(fn() { value = 1 }))
test "live dynamic call" { assert value == 1;@println(value) }
"#,
            "required:7\n1\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_jump_operands_retain_mutations() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"
mut int value = 0
fn change() int { value = 1;return 7 }
fn result() int { return change() }
@println("required:", result())
test "return operand" { assert value == 1;@println(value) }
"#,
                "required:7\n1\n",
            ),
            (
                r#"
mut int value = 0
fn message() str { @print("required:");value = 1;return "failure" }
fn fail() void! { throw message() }
_ = fail()
test "throw operand" { assert value == 1;@println(value) }
"#,
                "required:1\n",
            ),
            (
                r#"
mut int value = 0
fn change() int { value = 1;return 7 }
int unused = if true { true -> { break change() } _ -> { 0 } }
test "value break operand" { assert value == 1;@println(value) }
"#,
                "1\n",
            ),
        ],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_scope_restoration_retains_reachable_mutations() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut cases = Vec::new();
    for body in [
        "if false { true -> { return 0;value = 9 } _ -> {} }",
        "while false { return 0;value = 9 }",
        "_ = false and change()",
        "_ = true or change()",
        "for i in [0] { { break };value = 9 }",
        "for i in [0] { { continue };value = 9 }",
    ] {
        cases.push(format!(
            r#"
mut int value = 0
fn change() bool {{ value = 9;return true }}
fn required() int {{
    {body}
    value = value + 1
    return 7
}}
@println("required:", required())
test "reachable mutation" {{ assert value == 1;@println(value) }}
"#,
        ));
    }
    let cases: Vec<_> = cases
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_retained_dead_code_keeps_struct_and_helper_dependencies() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
struct Box { int value }
fn helper() int { return 9 }
fn retained() int {
    return 7
    Box box = Box { .value = helper() }
    _ = box.value
}
test "syntax dependencies" { assert retained() == 7;@println(retained()) }
"#,
            "7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_retained_dead_code_still_rejects_semantic_errors() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"fn retained() int { return 7;int invalid = true };test "dead invalid" { assert retained() == 7 }"#,
                "expected `int`, found `bool`",
            ),
            (
                r#"fn helper() int { return missing };fn retained() int { return 7;_ = helper() };test "dead helper" { assert retained() == 7 }"#,
                "missing",
            ),
            (
                r#"struct Box { Missing field };fn retained() int { return 7;Box box = Box { .field = 0 } };test "dead type" { assert retained() == 7 }"#,
                "Missing",
            ),
            (
                r#"fn retained() int { int value = 0;return 7;value = 1 };test "dead assignment" { assert retained() == 7 }"#,
                "cannot mutate immutable",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_dead_assignments_preserve_qualification_error_evidence() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                "import { \"library\" as lib };for i in [0] { break\nlib.missing = 1 };test \"qualification\" { assert true }",
                "does not export `missing`",
            ),
            (
                r#"import { "library" as lib };for i in [0] { continue;lib.missing = 1 };test "qualification" { assert true }"#,
                "does not export `missing`",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_boolean_dead_branches_exclude_writes_and_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    let mut sources = Vec::new();
    for body in [
        "if false { true -> { EFFECT } false -> {} }",
        "if not false { false -> { EFFECT } true -> {} }",
        "if true and not false { false -> { EFFECT } _ -> {} }",
        "if false or true { false -> { EFFECT } _ -> {} }",
        "if { false -> { EFFECT } _ -> {} }",
        "if true { false, false -> { EFFECT } false, true -> {} _ -> { EFFECT } }",
        "if false { true, false -> {} _ -> { EFFECT } }",
        "if true { _ -> {} true -> { EFFECT } }",
        "while false { EFFECT }",
        "while not (true or false) { EFFECT }",
        "while false and change() { EFFECT }",
        "if false and change() { true -> { EFFECT } _ -> {} }",
        "if true or change() { false -> { EFFECT } _ -> {} }",
        "if { not true -> { EFFECT } _ -> {} }",
    ] {
        for effect in ["value = 9", "_ = change()"] {
            sources.push(format!(
                r#"
mut int value = 0
fn change() bool {{ value = 9;return true }}
fn dead() int {{ {};return 7 }}
@println("excluded:", dead())
test "dead Boolean effects" {{ assert value == 0;@println(value) }}
"#,
                body.replace("EFFECT", effect),
            ));
        }
    }
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_short_circuits_exclude_rhs_calls() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "false and change()",
        "not true and change()",
        "(true and false) and change()",
        "true or change()",
        "not false or change()",
        "(false or true) or change()",
        "false and (true or change())",
        "true or (false and change())",
    ]
    .iter()
    .map(|expression| {
        format!(
            r#"
mut int value = 0
fn change() bool {{ value = 9;return true }}
fn dead() bool {{ return {expression} }}
@println("excluded:", dead())
test "dead RHS" {{ assert value == 0;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_dynamic_calls_exclude_opacity() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if false { true -> { _ = action() } _ -> {} }",
        "if { true -> {} _ -> { _ = action() } }",
        "while false { _ = action() }",
        "_ = false and action()",
        "_ = true or action()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
fn dead((fn() bool) action) int {{ {body};return 7 }}
@println("excluded:", dead(fn() bool {{ return true }}))
test "dead dynamic mutation" {{ assert value == 0;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_native_calls_exclude_opacity() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(directory.path().join("native.c"), "static int state; nc_abi_set_result set(void) { state = 9; } nc_abi_read_result read(void) { return state; }").unwrap();
    let sources: Vec<_> = [
        "if false { true -> { native.set() } _ -> {} }",
        "if { true -> {} _ -> { native.set() } }",
        "while false { native.set() }",
        "_ = false and mutate()",
        "_ = true or mutate()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
extern "native.c" as native {{ fn set() = "set" fn read() int = "read" }}
fn mutate() bool {{ native.set();return true }}
fn dead() int {{ {body};return 7 }}
@println("excluded:", dead())
native.set()
test "live native mutation" {{ assert native.read() == 9;@println(native.read()) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "9\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_await_does_not_retain_unrelated_output() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if false { true -> { _ = await task } _ -> {} }",
        "if { true -> {} _ -> { _ = await task } }",
        "while false { _ = await task }",
        "_ = false and await task",
        "_ = true or await task",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
fn produce() bool {{ @println("worker");return true }}
fut bool work = async produce()
fn dead(fut bool task) int {{ {body};return 7 }}
@println("excluded:", dead(work))
test "live await" {{ assert await work;@println("kept") }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "worker\nkept\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_ordered_patterns_stop_dead_comparisons_and_arms() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { false, true, change() -> {} _ -> { _ = change() } }",
        "if false { true, false, change() -> {} _ -> { _ = change() } }",
        "if { false, true, change() -> {} _ -> { _ = change() } }",
        "if true { true -> {} change() -> {} _ -> { _ = change() } }",
        "if true { unknown() -> {} true -> {} change() -> {} _ -> { _ = change() } }",
        "if { unknown() -> {} false, true -> {} change() -> {} _ -> { _ = change() } }",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
fn unknown() bool {{ return false }}
fn change() bool {{ value = 9;return true }}
fn dead() int {{ {body};return 7 }}
@println("excluded:", dead())
test "ordered dead effects" {{ assert value == 0;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "0\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_reached_mutations_and_pattern_effects_are_retained() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { false -> {} true -> { value = value + 1 } }",
        "if not true { true -> {} _ -> { _ = change() } }",
        "if { false -> {} true -> { _ = change() } _ -> {} }",
        "if true { false, true -> { _ = change() } _ -> {} }",
        "_ = true and change()",
        "_ = false or change()",
        "_ = change() and false",
        "_ = change() or true",
        "while change() { break }",
        "if change() { true -> {} _ -> {} }",
        "if true { probe() -> {} true -> {} _ -> {} }",
        "if true { false, probe(), true -> {} _ -> {} }",
        "if { probe() -> {} false, true -> {} _ -> {} }",
        "if { probe(), true -> {} _ -> {} }",
        "if { change() -> {} _ -> {} }",
        "if true { expected -> {} true -> { _ = change() } _ -> {} }",
        "if false { expected -> { _ = change() } _ -> {} }",
        "if unknown { true -> { _ = change() } false -> {} }",
        "_ = unknown and change()",
        "_ = expected or change()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
bool expected = false
bool unknown = true
fn change() bool {{ value = value + 1;return true }}
fn probe() bool {{ value = value + 1;return false }}
fn required() int {{ {body};return 7 }}
@println("required:", required())
test "reached Boolean effects" {{ assert value == 1;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_reached_dynamic_mutations_are_retained() {
    let directory = ncc::temp::Directory::new().unwrap();
    let sources: Vec<_> = [
        "if true { true -> { _ = action() } _ -> {} }",
        "if { action() -> {} _ -> {} }",
        "while action() { break }",
        "_ = true and action()",
        "_ = false or action()",
    ]
    .iter()
    .map(|body| {
        format!(
            r#"
mut int value = 0
fn required((fn() bool) action) int {{ {body};return 7 }}
@println("required:", required(fn() bool {{ value = 1;return true }}))
test "reached dynamic mutation" {{ assert value == 1;@println(value) }}
"#,
        )
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "required:7\n1\n"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Output);
}

#[test]
fn test_slicing_boolean_dead_syntax_keeps_type_and_value_dependencies() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[(
            r#"
struct Box { int value }
mut int target = 0
fn helper() int { return 9 }
fn condition() bool { return true }
fn retained() int {
    if false { true -> { Box box = Box { .value = helper() };target = box.value } _ -> {} }
    while false { Box box = Box { .value = helper() };_ = box.value }
    _ = false and condition()
    _ = true or condition()
    if { true -> {} condition() -> { _ = helper() } _ -> {} }
    return 7
}
test "dead syntax dependencies" { assert retained() == 7;assert target == 0;@println(retained()) }
"#,
            "7\n",
        )],
        &SlicingCliExpectation::Output,
    );
}

#[test]
fn test_slicing_boolean_dead_references_still_receive_semantic_checks() {
    let directory = ncc::temp::Directory::new().unwrap();
    assert_slicing_cli_cases(
        directory.path(),
        &[
            (
                r#"fn retained() { if false { true -> { int invalid = true } _ -> {} } };test "dead type" { retained() }"#,
                "expected `int`, found `bool`",
            ),
            (
                r#"fn helper() bool { return missing };fn retained() { _ = false and helper() };test "dead helper" { retained() }"#,
                "missing",
            ),
            (
                r#"fn helper() bool { return missing };fn retained() { _ = true or helper() };test "dead helper" { retained() }"#,
                "missing",
            ),
            (
                r#"struct Box { Missing field };fn retained() { while false { Box box = Box { .field = 0 } } };test "dead type" { retained() }"#,
                "Missing",
            ),
            (
                r#"int value = 0;fn retained() { if { true -> {} _ -> { value = 1 } } };test "dead assignment" { retained() }"#,
                "cannot mutate immutable",
            ),
            (
                r#"fn helper() bool { return missing };fn retained() { if true { false, true, helper() -> {} _ -> {} } };test "dead pattern" { retained() }"#,
                "missing",
            ),
            (
                r#"fn helper() bool { return missing };fn retained() { if { true -> {} helper() -> {} _ -> {} } };test "dead arm" { retained() }"#,
                "missing",
            ),
        ],
        &SlicingCliExpectation::Diagnostic,
    );
}

#[test]
fn test_slicing_boolean_dead_assignments_keep_qualification_evidence() {
    let directory = ncc::temp::Directory::new().unwrap();
    fs::write(
        directory.path().join("library.nc"),
        "pub fn good() int { return 1 }",
    )
    .unwrap();
    let sources: Vec<_> = [
        "if false { true -> { lib.missing = 1 } _ -> {} }",
        "if { true -> {} _ -> { lib.missing = 1 } }",
        "while false { lib.missing = 1 }",
    ]
    .iter()
    .map(|body| {
        format!("import {{ \"library\" as lib }};{body};test \"qualification\" {{ assert true }}")
    })
    .collect();
    let cases: Vec<_> = sources
        .iter()
        .map(|source| (source.as_str(), "does not export `missing`"))
        .collect();
    assert_slicing_cli_cases(directory.path(), &cases, &SlicingCliExpectation::Diagnostic);
}
