// NC concrete syntax. Semantic restrictions are enforced by ncc, not the editor.
const commaSep1 = rule => seq(rule, repeat(seq(',', rule)), optional(','));
const commaSep = rule => optional(commaSep1(rule));

module.exports = grammar({
  name: 'nc',
  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  conflicts: $ => [
    [$.parameter, $.function_type],
    [$.parameters, $.function_type],
    [$.call_expression, $.unary_expression, $.binary_expression],
    [$.call_expression, $.binary_expression],
    [$.named_type, $._expression],
  ],
  rules: {
    source_file: $ => repeat($._item),
    comment: _ => token(seq('//', /[^\r\n]*/)),
    identifier: _ => /[A-Za-z_][A-Za-z_0-9]*/,
    _item: $ => choice($.import_declaration, $.extern_declaration,
      $.function_declaration, $.struct_declaration, $.enum_declaration,
      $.type_declaration, $.test_declaration, $._statement),
    import_declaration: $ => seq('import', '{', repeat(seq($.string, 'as', field('alias', $.identifier), optional(','))), '}'),
    extern_declaration: $ => seq('extern', $.string, 'as', field('alias', $.identifier), '{', repeat($.function_signature), '}'),
    function_signature: $ => seq('fn', field('name', $.identifier), $.parameters, optional($._return_type), '=', $.string),
    function_declaration: $ => seq(optional('pub'), 'fn', field('name', $.identifier), optional($.type_parameters), $.parameters, optional($._return_type), field('body', $.block)),
    lambda_expression: $ => seq('fn', $.parameters, optional($._return_type), field('body', $.block)),
    parameters: $ => seq('(', commaSep($.parameter), ')'),
    parameter: $ => seq(field('type', $._type), field('name', $.identifier)),
    _return_type: $ => choice($._type, '!'),
    type_parameters: $ => seq('<', commaSep1(seq(optional('type'), $.identifier)), '>'),
    type_arguments: $ => seq('<', commaSep1($._type), '>'),
    struct_declaration: $ => seq(optional('pub'), 'struct', field('name', $.identifier), optional($.type_parameters), '{', repeat(seq($.field_declaration, optional(','))), '}'),
    field_declaration: $ => seq(field('type', $._type), field('name', $.identifier)),
    enum_declaration: $ => seq(optional('pub'), 'enum', field('name', $.identifier), optional($.type_parameters), '{', repeat(seq($.enum_variant, optional(','))), '}'),
    enum_variant: $ => seq(field('name', $.identifier), optional(seq('(', commaSep($._type), ')'))),
    type_declaration: $ => seq(optional('pub'), 'type', field('name', $.identifier), '=', field('type', $._type)),
    test_declaration: $ => seq('test', field('name', $.string), $.block),
    _type: $ => choice($.named_type, $.array_type, $.map_type, $.tuple_type,
      $.function_type, $.optional_type, $.error_type, $.future_type),
    named_type: $ => seq($.identifier, repeat(seq('.', $.identifier)), optional($.type_arguments)),
    array_type: $ => prec.left(2, seq($._type, '[', optional($.number), ']')),
    map_type: $ => prec.right(seq('[', $._type, ']', $._type)),
    tuple_type: $ => seq('(', commaSep1($._type), ')'),
    function_type: $ => seq('(', 'fn', '(', commaSep(seq($._type, optional($.identifier))), ')', optional($._return_type), ')'),
    optional_type: $ => prec.left(2, seq($._type, '?')),
    error_type: $ => prec.left(2, seq($._type, '!')),
    future_type: $ => prec.right(seq('fut', $._type)),
    _statement: $ => choice($.variable_declaration, $.assignment_statement,
      $.expression_statement, $.return_statement, $.throw_statement,
      $.break_statement, $.continue_statement, $.assert_statement,
      $.for_statement, $.while_statement, $.lock_statement, $.labeled_statement, $.block),
    block: $ => seq('{', repeat(choice($.function_declaration, $._statement)), '}'),
    variable_declaration: $ => prec.dynamic(10, seq(optional('pub'), optional('mut'), optional('mutex'),
      choice(commaSep1($.parameter), seq('fn', field('name', $.identifier))), '=', field('value', $._expression))),
    assignment_statement: $ => seq(field('left', $._expression), '=', field('right', $._expression)),
    expression_statement: $ => prec(-2, $._expression),
    return_statement: $ => prec.right(seq('return', optional(commaSep1($._expression)))),
    throw_statement: $ => seq('throw', $._expression),
    break_statement: $ => prec.right(seq('break', optional(choice(seq(':', $.identifier), $._expression)))),
    continue_statement: $ => prec.right(seq('continue', optional(seq(':', $.identifier)))),
    assert_statement: $ => seq('assert', $._expression),
    for_statement: $ => seq('for', field('name', $.identifier), 'in', field('value', $._expression), $.block),
    while_statement: $ => seq('while', field('condition', $._expression), $.block),
    lock_statement: $ => seq('lock', $.identifier, $.block),
    labeled_statement: $ => seq(field('label', $.identifier), ':', choice($.for_statement, $.while_statement, $.if_expression, $.lock_statement)),
    _expression: $ => choice($.identifier, $.builtin, $.number, $.string, $.multiline_string, $.character,
      $.boolean, $.none, $.last_index, $.array_expression, $.map_expression,
      $.tuple_expression, $.parenthesized_expression, $.struct_expression,
      $.call_expression, $.index_expression, $.member_expression, $.unary_expression,
      $.binary_expression, $.if_expression, $.lambda_expression, $.else_expression, $.catch_expression, $.cast_expression),
    builtin: $ => seq('@', $.identifier),
    cast_expression: $ => seq('@', 'as', '(', $._type, ',', $._expression, ')'),
    number: _ => token(choice(/0[xX][0-9a-fA-F_]+u?/, /0[bB][01_]+u?/, /0[oO][0-7_]+u?/, /[0-9][0-9_]*(\.[0-9][0-9_]*)?u?/)),
    boolean: _ => choice('true', 'false'),
    none: _ => 'none',
    last_index: _ => '$',
    string: $ => seq('"', repeat(choice($.string_content, $.escape_sequence, $.interpolation)), '"'),
    string_content: _ => token.immediate(/[^"\\{\r\n]+/),
    escape_sequence: _ => token.immediate(/\\[^\r\n]/),
    interpolation: $ => seq('{', $._expression, '}'),
    multiline_string: $ => seq('"""', repeat(choice($.multiline_content, $.escape_sequence, $.interpolation)), '"""'),
    multiline_content: _ => token.immediate(choice(/[^"\\{]+/, /"[^"\\{]/, /""[^"\\{]/)),
    character: _ => token(seq("'", repeat1(choice(/[^'\\\r\n]/, /\\[^\r\n]/)), "'")),
    array_expression: $ => seq('[', commaSep($._expression), ']'),
    map_expression: $ => seq('[', commaSep1($.map_entry), ']'),
    map_entry: $ => seq(field('key', $._expression), ':', field('value', $._expression)),
    tuple_expression: $ => seq('(', $._expression, ',', commaSep($._expression), ')'),
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    struct_expression: $ => seq(field('type', $.named_type), '{', commaSep1($.field_initializer), '}'),
    field_initializer: $ => seq('.', field('name', $.identifier), '=', field('value', $._expression)),
    call_expression: $ => prec.left(15, seq(field('function', $._expression), optional($.type_arguments), field('arguments', $.arguments))),
    arguments: $ => seq('(', commaSep($._expression), ')'),
    index_expression: $ => prec.left(15, seq(field('value', $._expression), '[', field('index', $._expression), ']')),
    member_expression: $ => prec.left(15, seq(field('value', $._expression), '.', field('member', $.identifier))),
    unary_expression: $ => prec(13, seq(choice('-', 'not', '!', 'async', 'await', 'try'), $._expression)),
    binary_expression: $ => choice(...[
      [1, ['or']], [2, ['and']], [3, ['|']], [4, ['^']], [5, ['&']],
      [6, ['==', '!=']], [7, ['<', '>', '<=', '>=', 'in']], [8, ['<<', '>>']],
      [9, ['<>']], [10, ['+', '-']], [11, ['*', '/', '%']],
    ].map(([precedence, operators]) => prec.left(precedence, seq(field('left', $._expression), field('operator', operators.length === 1 ? operators[0] : choice(...operators)), field('right', $._expression)))),
      prec.right(14, seq(field('left', $._expression), '**', field('right', $._expression)))),
    if_expression: $ => seq('if', optional(field('subject', $._expression)), '{', repeat($.match_arm), '}'),
    match_arm: $ => seq(commaSep1($._expression), '->', $.block),
    else_expression: $ => prec.right(0, seq($._expression, 'else', choice($._expression, $.block))),
    catch_expression: $ => prec.left(0, seq($._expression, 'catch', field('name', $.identifier), $.block)),
  },
});
