// Convert the Unicode 16 tables shipped by unicode-segmentation 1.12.0.
// Usage: node scripts/unicode-tables.mjs /path/to/unicode-segmentation/src/tables.rs
// Outputs Rust data; Hangul syllable categories are calculated algorithmically.
import fs from 'node:fs';
const source = fs.readFileSync(process.argv[2], 'utf8');
const names = ['Any','CR','Control','Extend','Extended_Pictographic','InCB_Consonant','L','LF','LV','LVT','Prepend','Regional_Indicator','SpacingMark','T','V','ZWJ'];
const section = name => source.split(`const ${name}:`)[1].split('];')[0];
const categories = [...section('grapheme_cat_table').matchAll(/\('\\u\{([0-9a-f]+)\}',\s*'\\u\{([0-9a-f]+)\}',\s*GC_(\w+)\)/gi)].map(m => [parseInt(m[1],16),parseInt(m[2],16),names.indexOf(m[3])]);
const extends_ = [...section('InCB_Extend_table').matchAll(/\('\\u\{([0-9a-f]+)\}',\s*'\\u\{([0-9a-f]+)\}'\)/gi)].map(m => [parseInt(m[1],16),parseInt(m[2],16),16]);
if (categories.length < 1000 || extends_.length < 100) throw Error('unexpected table format');
const boundaries = [...new Set([...categories,...extends_].flatMap(([lo,hi]) => [lo,hi+1]))].sort((a,b) => a-b);
const ranges = [];
for (let i=0;i<boundaries.length-1;i++) {
  const lo=boundaries[i], hi=boundaries[i+1]-1;
  if (lo>=0xac00 && hi<=0xd7a3) continue;
  const category=categories.find(([a,b])=>a<=lo && lo<=b)?.[2] ?? 0;
  const extend=extends_.some(([a,b])=>a<=lo && lo<=b) ? 16 : 0;
  if (!(category|extend)) continue;
  const previous=ranges.at(-1);
  if (previous && previous[1]+1===lo && previous[2]===(category|extend)) previous[1]=hi;
  else ranges.push([lo,hi,category|extend]);
}
console.log('// Unicode 16.0.0 data, derived from unicode-segmentation 1.12.0.\n// Copyright 2012-2018 The Rust Project Developers; MIT, see UNICODE-LICENSE.\n// Generated by scripts/unicode-tables.mjs.\npub const RANGES: &[(u32,u32,u8)] = &[');
for (const [lo,hi,value] of ranges) console.log(`    (0x${lo.toString(16)},0x${hi.toString(16)},${value}),`);
console.log('];');
