// Generate Unicode 18 tables from the unmodified official UCD files.
// Usage: node scripts/unicode-tables.mjs [tests/fixtures/unicode] > src/unicode_data.rs
// Hangul categories are computed at lookup time; other properties remain independent.
import fs from "node:fs";
import path from "node:path";

const directory = process.argv[2] ?? "tests/fixtures/unicode";
const version = "18.0.0";
const categories = new Map([
  ["CR", 1],
  ["Control", 2],
  ["Extend", 3],
  ["L", 6],
  ["LF", 7],
  ["LV", 8],
  ["LVT", 9],
  ["Prepend", 10],
  ["Regional_Indicator", 11],
  ["SpacingMark", 12],
  ["T", 13],
  ["V", 14],
  ["ZWJ", 15],
]);
const flags = new Map([
  ["Consonant", 32],
  ["Linker", 64],
  ["Extend", 128],
]);
const values = new Uint8Array(0x110000);

function records(file, signature) {
  const source = fs.readFileSync(path.join(directory, file), "utf8");
  if (!source.includes(signature))
    throw Error(`${file}: not Unicode ${version}`);
  return source.split("\n").flatMap((line) => {
    const content = line.split("#")[0].trim();
    if (!content) return [];
    const [range, ...properties] = content
      .split(";")
      .map((field) => field.trim());
    if (!/^[0-9A-F]{4,6}(?:\.\.[0-9A-F]{4,6})?$/.test(range)) {
      throw Error(`${file}: malformed range ${range}`);
    }
    const [lo, hi = lo] = range.split("..").map((value) => parseInt(value, 16));
    if (lo > hi || hi >= values.length)
      throw Error(`${file}: invalid range ${range}`);
    return [[lo, hi, properties]];
  });
}

for (const [lo, hi, [name]] of records(
  "GraphemeBreakProperty.txt",
  `GraphemeBreakProperty-${version}.txt`,
)) {
  const category = categories.get(name);
  if (category === undefined) throw Error(`unknown grapheme category ${name}`);
  for (let c = lo; c <= hi; ++c) {
    if (values[c] & 15) throw Error(`overlapping grapheme categories at ${c}`);
    values[c] |= category;
  }
}
let indicRecords = 0;
for (const [lo, hi, [property, name]] of records(
  "DerivedCoreProperties.txt",
  `DerivedCoreProperties-${version}.txt`,
)) {
  if (property !== "InCB") continue;
  const flag = flags.get(name);
  if (flag === undefined) throw Error(`unknown InCB value ${name}`);
  ++indicRecords;
  for (let c = lo; c <= hi; ++c) values[c] |= flag;
}
let emojiRecords = 0;
for (const [lo, hi, [property]] of records(
  "emoji-data.txt",
  `Version: ${version}\n`,
)) {
  if (property !== "Extended_Pictographic") continue;
  ++emojiRecords;
  for (let c = lo; c <= hi; ++c) values[c] |= 16;
}
if (!indicRecords || !emojiRecords)
  throw Error("missing InCB or emoji records");
// Clear only algorithmic GCB bits, not overlapping independent properties.
for (let c = 0xac00; c <= 0xd7a3; ++c) values[c] &= 0xf0;
const ranges = [];
for (let lo = 0; lo < values.length;) {
  let hi = lo;
  while (hi + 1 < values.length && values[hi + 1] === values[lo]) ++hi;
  if (values[lo]) ranges.push([lo, hi, values[lo]]);
  lo = hi + 1;
}
console.log(`// Unicode ${version}; official GraphemeBreakProperty, DerivedCoreProperties, emoji-data.
// © 2026 Unicode, Inc. Unicode License V3; see UNICODE-LICENSE.
// Generated by scripts/unicode-tables.mjs; do not edit.
// Low nibble: GCB; flags: EP=16, InCB Consonant=32, Linker=64, Extend=128.
pub const RANGES: &[(u32, u32, u8)] = &[`);
for (const [lo, hi, value] of ranges) {
  console.log(`    (0x${lo.toString(16)}, 0x${hi.toString(16)}, ${value}),`);
}
console.log("];");
