//! C emission uses the types recorded during semantic checking. Expressions
//! are evaluated into temporaries to preserve NC's left-to-right evaluation.
use crate::{
    ast::*,
    diagnostic::Diagnostics,
    sema::{CheckedModule, integer},
};
use std::collections::{BTreeSet, HashMap};

pub fn emit(checked: &CheckedModule) -> Result<String, Diagnostics> {
    let mut e = Emitter {
        checked,
        headers: BTreeSet::new(),
        helpers: BTreeSet::new(),
        out: String::new(),
        scopes: vec![HashMap::new()],
        next: 0,
        loops: vec![],
    };
    let mut declarations = String::new();
    for item in &checked.module.items {
        match item {
            Item::Function(f) => {
                if !f.generics.is_empty() || f.throws {
                    return unsupported("generic or throwing functions");
                }
                let ret = e.c_type(&f.return_type)?;
                let params = f
                    .params
                    .iter()
                    .map(|p| e.c_type(&p.ty))
                    .collect::<Result<Vec<_>, _>>()?;
                declarations.push_str(&format!(
                    "{ret} nc_fn_{}({});\n",
                    f.name,
                    if params.is_empty() {
                        "void".into()
                    } else {
                        params.join(", ")
                    }
                ));
            }
            Item::Global(v) => {
                let ty = e.c_type(&v.ty)?;
                let name = e.bind(pattern_name(&v.pattern)?);
                declarations.push_str(&format!("static {ty} {name};\n"));
            }
            Item::Import { .. } | Item::Extern { .. } => {
                return unsupported("module or external linkage");
            }
            Item::Struct(_) | Item::Enum(_) | Item::TypeAlias { .. } => {
                return unsupported("user-defined types");
            }
            _ => {}
        }
    }
    let global_names = e.scopes[0].clone();
    for item in &checked.module.items {
        if let Item::Function(f) = item {
            e.scopes.push(HashMap::new());
            let ret = e.c_type(&f.return_type)?;
            let mut params = vec![];
            for p in &f.params {
                let ty = e.c_type(&p.ty)?;
                let name = e.bind(&p.name);
                params.push(format!("{ty} {name}"));
            }
            e.line(format!(
                "{ret} nc_fn_{}({}) {{",
                f.name,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            ));
            e.block(&f.body)?;
            e.line("}");
            e.scopes.pop();
        }
    }
    e.scopes[0].clear();
    e.line("int main(void) {");
    for item in &checked.module.items {
        match item {
            Item::Global(v) => {
                let value = e.expr(&v.value)?;
                let n = pattern_name(&v.pattern)?;
                let name = &global_names[n];
                e.line(format!("{name} = {value};"));
                e.scopes[0].insert(n.into(), name.clone());
            }
            Item::Statement(s) => e.statement(s)?,
            Item::Test { body, .. } => {
                e.line("{");
                e.block(body)?;
                e.line("}");
            }
            _ => {}
        }
    }
    e.line("return 0;\n}");
    let mut output = String::from("/* Generated by ncc. */\n");
    for header in &e.headers {
        output.push_str(&format!("#include <{header}>\n"));
    }
    for helper in &e.helpers {
        output.push_str(helper);
        output.push('\n');
    }
    output.push_str(&declarations);
    output.push_str(&e.out);
    Ok(output)
}
fn unsupported<T>(feature: &str) -> Result<T, Diagnostics> {
    Err(Diagnostics::one(
        format!("C backend does not yet implement {feature}"),
        0..0,
    ))
}
fn pattern_name(pattern: &Pattern) -> Result<&str, Diagnostics> {
    if let Pattern::Name(name) = pattern {
        Ok(name)
    } else {
        unsupported("destructuring")
    }
}

struct Emitter<'a> {
    checked: &'a CheckedModule,
    headers: BTreeSet<&'static str>,
    helpers: BTreeSet<String>,
    out: String,
    scopes: Vec<HashMap<String, String>>,
    next: usize,
    loops: Vec<(Option<String>, String, String)>,
}
impl Emitter<'_> {
    fn line(&mut self, text: impl AsRef<str>) {
        self.out.push_str(text.as_ref());
        self.out.push('\n');
    }
    fn fresh(&mut self) -> String {
        self.next += 1;
        format!("nc_v{}", self.next)
    }
    fn bind(&mut self, name: &str) -> String {
        let id = self.fresh();
        self.scopes
            .last_mut()
            .unwrap()
            .insert(name.into(), id.clone());
        id
    }
    fn name(&self, name: &str) -> String {
        self.scopes
            .iter()
            .rev()
            .find_map(|s| s.get(name))
            .cloned()
            .unwrap_or_else(|| format!("nc_fn_{name}"))
    }
    fn ty(&self, expr: &Expr) -> Result<Type, Diagnostics> {
        self.checked
            .expression_types
            .get(&(expr as *const Expr as usize))
            .cloned()
            .ok_or_else(|| Diagnostics::one("internal error: missing expression type", 0..0))
    }
    fn c_type(&mut self, ty: &Type) -> Result<&'static str, Diagnostics> {
        Ok(match ty {
            Type::Named(n, _) => match n.as_str() {
                "void" => "void",
                "float" => "double",
                "str" | "char" => "const char *",
                "bool" => {
                    self.headers.insert("stdbool.h");
                    "bool"
                }
                "int" => {
                    self.headers.insert("stdint.h");
                    "int64_t"
                }
                "uint" => {
                    self.headers.insert("stdint.h");
                    "uint64_t"
                }
                "byte" => {
                    self.headers.insert("stdint.h");
                    "uint8_t"
                }
                _ => return unsupported("this value type"),
            },
            _ => return unsupported("composite value types"),
        })
    }
    fn temp(&mut self, expr: &Expr, value: String) -> Result<String, Diagnostics> {
        let ty = self.ty(expr)?;
        if ty == Type::void() {
            self.line(format!("{value};"));
            return Ok(String::new());
        }
        let ct = self.c_type(&ty)?;
        let id = self.fresh();
        self.line(format!("{ct} {id} = {value};"));
        Ok(id)
    }
    fn panic_support(&mut self) {
        self.headers.extend(["stdio.h", "stdlib.h"]);
        self.helpers.insert("static void nc_panic(const char *message) { fprintf(stderr, \"panic: %s\\n\", message); exit(1); }".into());
    }
    fn block(&mut self, body: &Block) -> Result<(), Diagnostics> {
        self.scopes.push(HashMap::new());
        for statement in &body.statements {
            self.statement(statement)?;
        }
        self.scopes.pop();
        Ok(())
    }
    fn statement(&mut self, statement: &Stmt) -> Result<(), Diagnostics> {
        match statement {
            Stmt::Block(block) => {
                self.line("{");
                self.block(block)?;
                self.line("}");
            }
            Stmt::Var(v) => {
                if v.mutex {
                    return unsupported("mutexes");
                }
                let value = self.expr(&v.value)?;
                let ty = self.c_type(&v.ty)?;
                let name = self.bind(pattern_name(&v.pattern)?);
                self.line(format!("{ty} {name} = {value};"));
            }
            Stmt::Assign { target, value } => {
                let value = self.expr(value)?;
                match target {
                    Expr::Name(n) if n == "_" => {}
                    Expr::Name(n) => self.line(format!("{} = {value};", self.name(n))),
                    _ => return unsupported("composite assignment"),
                }
            }
            Stmt::Expr(Expr::If { subject, arms }) => self.conditional(subject.as_deref(), arms)?,
            Stmt::Expr(value) => {
                self.expr(value)?;
            }
            Stmt::Return(value) => {
                let value = value
                    .as_ref()
                    .map(|v| self.expr(v))
                    .transpose()?
                    .unwrap_or_default();
                self.line(format!("return {value};"));
            }
            Stmt::Throw(value) => {
                let value = self.expr(value)?;
                self.panic_support();
                self.line(format!("nc_panic({value});"));
            }
            Stmt::Assert(value) => {
                let value = self.expr(value)?;
                self.panic_support();
                self.line(format!("if (!({value})) nc_panic(\"assertion failed\");"));
            }
            Stmt::While {
                label,
                condition,
                body,
            } => {
                let start = self.fresh();
                let end = self.fresh();
                self.loops.push((label.clone(), start.clone(), end.clone()));
                self.line(format!("{start}:; {{"));
                let condition = self.expr(condition)?;
                self.line(format!("if (!({condition})) goto {end};"));
                self.block(body)?;
                self.line(format!("}} goto {start};\n{end}:;"));
                self.loops.pop();
            }
            Stmt::Break(value, label) => {
                if value.is_some() {
                    return unsupported("value-carrying break");
                }
                let (_, _, end) = self.loop_target(label)?;
                self.line(format!("goto {end};"));
            }
            Stmt::Continue(label) => {
                let (_, start, _) = self.loop_target(label)?;
                self.line(format!("goto {start};"));
            }
            Stmt::For { .. } => return unsupported("for loops"),
            Stmt::Lock { .. } => return unsupported("mutex locks"),
        }
        Ok(())
    }
    fn loop_target(
        &self,
        label: &Option<String>,
    ) -> Result<(Option<String>, String, String), Diagnostics> {
        self.loops
            .iter()
            .rev()
            .find(|(name, _, _)| label.is_none() || name == label)
            .cloned()
            .ok_or_else(|| Diagnostics::one("invalid loop target", 0..0))
    }
    fn conditional(
        &mut self,
        subject: Option<&Expr>,
        arms: &[(Vec<Pattern>, Block)],
    ) -> Result<(), Diagnostics> {
        let value = subject.map(|x| self.expr(x)).transpose()?;
        let done = self.fresh();
        for (patterns, body) in arms {
            let branch = self.fresh();
            let next = self.fresh();
            for pattern in patterns {
                match pattern {
                    Pattern::Wildcard => self.line(format!("goto {branch};")),
                    Pattern::Literal(pattern) => {
                        let p = self.expr(pattern)?;
                        let condition = if let Some(value) = &value {
                            self.equality(value, &p, &self.ty(pattern)?)?
                        } else {
                            p
                        };
                        self.line(format!("if ({condition}) goto {branch};"));
                    }
                    _ => return unsupported("binding patterns"),
                }
            }
            self.line(format!("goto {next};\n{branch}:; {{"));
            self.block(body)?;
            self.line(format!("}} goto {done};\n{next}:;"));
        }
        self.line(format!("{done}:;"));
        Ok(())
    }
    fn equality(&mut self, left: &str, right: &str, ty: &Type) -> Result<String, Diagnostics> {
        if matches!(ty, Type::Named(n, _) if n == "str" || n == "char") {
            self.headers.insert("string.h");
            Ok(format!("strcmp({left}, {right}) == 0"))
        } else {
            Ok(format!("{left} == {right}"))
        }
    }
    fn expr(&mut self, e: &Expr) -> Result<String, Diagnostics> {
        let value = match e {
            Expr::Int(n) => {
                let n = integer(n)?;
                if matches!(self.ty(e)?, Type::Named(n, _) if n == "uint") {
                    format!("{n}ULL")
                } else {
                    format!("{n}LL")
                }
            }
            Expr::Float(n) => n.clone(),
            Expr::String(s) | Expr::Char(s) => c_string(s),
            Expr::Bool(b) => {
                self.headers.insert("stdbool.h");
                b.to_string()
            }
            Expr::Name(n) => self.name(n),
            Expr::Cast { ty, value } => {
                let value = self.expr(value)?;
                let ct = self.c_type(ty)?;
                format!("(({ct})({value}))")
            }
            Expr::Unary { op, value } => {
                let value = self.expr(value)?;
                format!(
                    "({}{value})",
                    match op {
                        UnaryOp::Neg => "-",
                        UnaryOp::Not => "!",
                        UnaryOp::BitNot => "~",
                    }
                )
            }
            Expr::Binary { left, op, right } => {
                let l = self.expr(left)?;
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.headers.insert("stdbool.h");
                    let result = self.fresh();
                    self.line(format!("bool {result} = {l};"));
                    self.line(format!(
                        "if ({}{result}) {{",
                        if *op == BinaryOp::Or { "!" } else { "" }
                    ));
                    let r = self.expr(right)?;
                    self.line(format!("{result} = {r};\n}}"));
                    return Ok(result);
                }
                let r = self.expr(right)?;
                match op {
                    BinaryOp::Eq | BinaryOp::Ne => {
                        let eq = self.equality(&l, &r, &self.ty(left)?)?;
                        format!("{}({eq})", if *op == BinaryOp::Ne { "!" } else { "" })
                    }
                    BinaryOp::Pow => return unsupported("exponentiation"),
                    BinaryOp::Concat | BinaryOp::In => return unsupported("container operators"),
                    _ => format!("({l} {} {r})", operator(*op)),
                }
            }
            Expr::Call { callee, args, .. } => {
                if let Expr::Name(name) = &**callee {
                    if name.starts_with('@') {
                        self.headers.insert("stdio.h");
                        let stream = if name.starts_with("@e") {
                            "stderr"
                        } else {
                            "stdout"
                        };
                        for arg in args {
                            let value = self.expr(arg)?;
                            let ty = self.ty(arg)?;
                            let (fmt, value) = match ty {
                                Type::Named(n, _) => match n.as_str() {
                                    "str" | "char" => ("%s", value),
                                    "bool" => ("%s", format!("{value} ? \"true\" : \"false\"")),
                                    "float" => ("%.17g", value),
                                    "uint" | "byte" => {
                                        ("%llu", format!("(unsigned long long){value}"))
                                    }
                                    _ => ("%lld", format!("(long long){value}")),
                                },
                                _ => return unsupported("printing composite types"),
                            };
                            self.line(format!("fprintf({stream}, \"{fmt}\", {value});"));
                        }
                        if name.ends_with("println") {
                            self.line(format!("fputc('\\n', {stream});"));
                        }
                        return Ok(String::new());
                    }
                }
                let callee = self.expr(callee)?;
                let args = args
                    .iter()
                    .map(|a| self.expr(a))
                    .collect::<Result<Vec<_>, _>>()?;
                format!("{callee}({})", args.join(", "))
            }
            _ => return unsupported("this expression"),
        };
        if matches!(e, Expr::Name(_)) {
            Ok(value)
        } else {
            self.temp(e, value)
        }
    }
}
fn operator(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Mod => "%",
        BinaryOp::Lt => "<",
        BinaryOp::Le => "<=",
        BinaryOp::Gt => ">",
        BinaryOp::Ge => ">=",
        BinaryOp::BitAnd => "&",
        BinaryOp::BitOr => "|",
        BinaryOp::BitXor => "^",
        BinaryOp::Shl => "<<",
        BinaryOp::Shr => ">>",
        _ => unreachable!(),
    }
}
fn c_string(value: &str) -> String {
    let mut s = String::from("\"");
    for b in value.bytes() {
        match b {
            b'"' => s.push_str("\\\""),
            b'\\' => s.push_str("\\\\"),
            32..=126 => s.push(b as char),
            _ => s.push_str(&format!("\\{b:03o}")),
        }
    }
    s.push('"');
    s
}
