use crate::{ast::*, sema::CheckedModule};

/// Emit portable C99 for NC's scalar and function subset.
pub fn emit(checked: &CheckedModule) -> String {
    let headers = Headers::from_items(&checked.module.items);
    let mut source = String::from("/* Generated by ncc. */\n");
    if headers.stdint {
        source.push_str("#include <stdint.h>\n");
    }
    if headers.stdbool {
        source.push_str("#include <stdbool.h>\n");
    }
    if headers.stdio {
        source.push_str("#include <stdio.h>\n");
    }
    source.push('\n');
    let mut e = Emitter {
        out: source,
        indent: 0,
    };
    for item in &checked.module.items {
        if let Item::Function(f) = item {
            e.line(&format!(
                "{} {}({});",
                c_type(&f.return_type),
                f.name,
                params(&f.params)
            ));
        }
    }
    e.line("");
    for item in &checked.module.items {
        match item {
            Item::Global(v) => e.global(v),
            Item::Function(f) => e.function(f),
            _ => {}
        }
    }
    e.line("int main(void) {");
    e.indent += 1;
    for item in &checked.module.items {
        match item {
            Item::Test { body, .. } => e.block(body),
            Item::Statement(statement) => e.statement(statement),
            _ => {}
        }
    }
    e.line("return 0;");
    e.indent -= 1;
    e.line("}");
    e.out
}

#[derive(Default)]
struct Headers {
    stdint: bool,
    stdbool: bool,
    stdio: bool,
}
impl Headers {
    fn from_items(items: &[Item]) -> Self {
        let mut headers = Self::default();
        for item in items {
            headers.item(item);
        }
        headers
    }
    fn item(&mut self, item: &Item) {
        match item {
            Item::Global(variable) => {
                self.ty(&variable.ty);
                self.expr(&variable.value);
            }
            Item::Statement(statement) => self.statement(statement),
            Item::Function(function) => {
                self.ty(&function.return_type);
                for parameter in &function.params {
                    self.ty(&parameter.ty);
                }
                self.block(&function.body);
            }
            Item::Test { body, .. } => self.block(body),
            _ => {}
        }
    }
    fn ty(&mut self, ty: &Type) {
        match ty {
            Type::Named(name, _) if name == "bool" => self.stdbool = true,
            Type::Named(name, _) if matches!(name.as_str(), "void" | "float" | "str" | "char") => {}
            Type::Named(_, _)
            | Type::Array(_, _)
            | Type::Map(_, _)
            | Type::Tuple(_)
            | Type::Function(_, _)
            | Type::Optional(_)
            | Type::ErrorUnion(_)
            | Type::Future(_) => self.stdint = true,
        }
    }
    fn block(&mut self, block: &Block) {
        for statement in &block.statements {
            self.statement(statement);
        }
    }
    fn statement(&mut self, statement: &Stmt) {
        match statement {
            Stmt::Var(variable) => {
                self.ty(&variable.ty);
                self.expr(&variable.value);
            }
            Stmt::Assign { target, value } => {
                self.expr(target);
                self.expr(value);
            }
            Stmt::Expr(expr) | Stmt::Assert(expr) | Stmt::Throw(expr) => {
                if matches!(statement, Stmt::Assert(_) | Stmt::Throw(_)) || is_print(expr) {
                    self.stdio = true;
                }
                self.expr(expr);
            }
            Stmt::Return(value) | Stmt::Break(value, _) => {
                if let Some(value) = value {
                    self.expr(value);
                }
            }
            Stmt::While {
                condition, body, ..
            } => {
                self.expr(condition);
                self.block(body);
            }
            Stmt::For { iterable, body, .. } => {
                self.stdint = true;
                self.expr(iterable);
                self.block(body);
            }
            Stmt::Lock { body, .. } => self.block(body),
            Stmt::Continue(_) => {}
        }
    }
    fn expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Unary { value, .. }
            | Expr::Async(value)
            | Expr::Await(value)
            | Expr::Try(value) => self.expr(value),
            Expr::Binary { left, right, .. } => {
                self.expr(left);
                self.expr(right);
            }
            Expr::Call { callee, args, .. } => {
                if is_print(expr) {
                    self.stdio = true;
                }
                self.expr(callee);
                for arg in args {
                    self.expr(arg);
                }
            }
            Expr::Index { object, index } => {
                self.expr(object);
                self.expr(index);
            }
            Expr::Member { object, .. } => self.expr(object),
            Expr::Array(values) | Expr::Tuple(values) => {
                for value in values {
                    self.expr(value);
                }
            }
            Expr::Map(entries) => {
                for (key, value) in entries {
                    self.expr(key);
                    self.expr(value);
                }
            }
            Expr::StructInit { fields, .. } => {
                for (_, value) in fields {
                    self.expr(value);
                }
            }
            Expr::If { subject, arms } => {
                if let Some(subject) = subject {
                    self.expr(subject);
                }
                for (_, body) in arms {
                    self.block(body);
                }
            }
            Expr::Else { value, fallback }
            | Expr::Catch {
                value,
                body: fallback,
                ..
            } => {
                self.expr(value);
                self.block(fallback);
            }
            _ => {}
        }
    }
}

fn is_print(expr: &Expr) -> bool {
    matches!(expr, Expr::Call { callee, .. } if matches!(&**callee, Expr::Name(name) if matches!(name.as_str(), "@print" | "@println" | "@eprint" | "@eprintln")))
}

struct Emitter {
    out: String,
    indent: usize,
}
impl Emitter {
    fn line(&mut self, text: &str) {
        self.out.push_str(&"  ".repeat(self.indent));
        self.out.push_str(text);
        self.out.push('\n');
    }
    fn global(&mut self, v: &VarDecl) {
        self.line(&format!(
            "{} {} = {};",
            c_type(&v.ty),
            name(&v.pattern),
            self.expr(&v.value)
        ));
    }
    fn function(&mut self, f: &Function) {
        self.line(&format!(
            "{} {}({}) {{",
            c_type(&f.return_type),
            f.name,
            params(&f.params)
        ));
        self.indent += 1;
        self.block(&f.body);
        self.indent -= 1;
        self.line("}");
        self.line("");
    }
    fn block(&mut self, b: &Block) {
        for s in &b.statements {
            self.statement(s);
        }
    }
    fn statement(&mut self, s: &Stmt) {
        match s {
            Stmt::Var(v) => self.line(&format!(
                "{} {} = {};",
                c_type(&v.ty),
                name(&v.pattern),
                self.expr(&v.value)
            )),
            Stmt::Assign { target, value } => {
                self.line(&format!("{} = {};", self.expr(target), self.expr(value)))
            }
            Stmt::Expr(Expr::If { subject, arms }) => self.if_statement(subject.as_deref(), arms),
            Stmt::Expr(e) => {
                if self.builtin_print(e) {
                    return;
                }
                self.line(&format!("{};", self.expr(e)));
            }
            Stmt::Return(value) => self.line(
                &value
                    .as_ref()
                    .map_or_else(|| "return;".into(), |v| format!("return {};", self.expr(v))),
            ),
            Stmt::Throw(value) => {
                self.line(&format!("fputs({}, stderr);", self.expr(value)));
                self.line("return 1;");
            }
            Stmt::Assert(value) => self.line(&format!(
                "if (!({})) {{ fputs(\"assertion failed\\n\", stderr); return 1; }}",
                self.expr(value)
            )),
            Stmt::While {
                condition, body, ..
            } => {
                self.line(&format!("while ({}) {{", self.expr(condition)));
                self.indent += 1;
                self.block(body);
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_, _) => self.line("break;"),
            Stmt::Continue(_) => self.line("continue;"),
            Stmt::Lock { body, .. } => self.block(body),
            Stmt::For {
                name: loop_name,
                body,
                ..
            } => {
                self.line("for (uint64_t __nc_i = 0; __nc_i < 0; ++__nc_i) {");
                self.indent += 1;
                self.line(&format!("uint64_t {loop_name} = __nc_i;"));
                self.block(body);
                self.indent -= 1;
                self.line("}");
            }
        }
    }
    fn if_statement(&mut self, subject: Option<&Expr>, arms: &[(Vec<Pattern>, Block)]) {
        for (index, (patterns, body)) in arms.iter().enumerate() {
            let fallback = matches!(patterns.as_slice(), [Pattern::Wildcard]);
            let condition = if fallback {
                None
            } else {
                let checks = patterns
                    .iter()
                    .map(|pattern| match (subject, pattern) {
                        (Some(value), Pattern::Literal(literal)) => {
                            format!("{} == {}", self.expr(value), self.expr(literal))
                        }
                        (None, Pattern::Literal(condition)) => self.expr(condition),
                        _ => "false".into(),
                    })
                    .collect::<Vec<_>>()
                    .join(" || ");
                Some(checks)
            };
            if index == 0 {
                self.line(&condition.map_or_else(|| "{".into(), |c| format!("if ({c}) {{")));
            } else if let Some(condition) = condition {
                self.line(&format!("else if ({condition}) {{"));
            } else {
                self.line("else {");
            }
            self.indent += 1;
            self.block(body);
            self.indent -= 1;
            self.line("}");
        }
    }
    fn builtin_print(&mut self, e: &Expr) -> bool {
        let Expr::Call { callee, args, .. } = e else {
            return false;
        };
        let Expr::Name(n) = &**callee else {
            return false;
        };
        if !matches!(n.as_str(), "@print" | "@println" | "@eprint" | "@eprintln") {
            return false;
        }
        let stream = if n.contains("eprint") {
            "stderr"
        } else {
            "stdout"
        };
        for arg in args {
            let (format, value) = match arg {
                Expr::String(_) | Expr::Char(_) => ("%s", self.expr(arg)),
                Expr::Float(_) => ("%g", self.expr(arg)),
                _ => ("%lld", format!("(long long)({})", self.expr(arg))),
            };
            self.line(&format!("fprintf({stream}, \"{format}\", {value});"));
        }
        if n.ends_with("println") {
            self.line(&format!("fputc('\\n', {stream});"));
        }
        true
    }
    fn expr(&self, e: &Expr) -> String {
        match e {
            Expr::Int(n) => n.trim_end_matches('u').into(),
            Expr::Float(n) => n.clone(),
            Expr::String(s) | Expr::Char(s) => c_string(s),
            Expr::Bool(v) => v.to_string(),
            Expr::None => "((void *)0)".into(),
            Expr::Name(n) => n.clone(),
            Expr::Discard => "0".into(),
            Expr::Unary { op, value } => format!("({}{})", unary(*op), self.expr(value)),
            Expr::Binary { left, op, right } => {
                format!("({} {} {})", self.expr(left), binary(*op), self.expr(right))
            }
            Expr::Call { callee, args, .. } => format!(
                "{}({})",
                self.expr(callee),
                args.iter()
                    .map(|x| self.expr(x))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Expr::Member { object, name } => format!("{}.{}", self.expr(object), name),
            Expr::Index { object, index } => format!("{}[{}]", self.expr(object), self.expr(index)),
            _ => "0 /* unsupported NC expression */".into(),
        }
    }
}
fn c_type(t: &Type) -> &'static str {
    match t {
        Type::Named(n, _) if n == "void" => "void",
        Type::Named(n, _) if n == "bool" => "bool",
        Type::Named(n, _) if n == "float" => "double",
        Type::Named(n, _) if n == "str" || n == "char" => "const char *",
        Type::Named(n, _) if n == "uint" || n == "byte" => "uint64_t",
        _ => "int64_t",
    }
}
fn params(xs: &[Param]) -> String {
    if xs.is_empty() {
        "void".into()
    } else {
        xs.iter()
            .map(|x| format!("{} {}", c_type(&x.ty), x.name))
            .collect::<Vec<_>>()
            .join(", ")
    }
}
fn name(p: &Pattern) -> &str {
    match p {
        Pattern::Name(n) => n,
        _ => "__nc_value",
    }
}
fn unary(op: UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg => "-",
        UnaryOp::Not => "!",
        UnaryOp::BitNot => "~",
    }
}
fn binary(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Mod => "%",
        BinaryOp::Pow => "^",
        BinaryOp::Concat => "+",
        BinaryOp::Eq => "==",
        BinaryOp::Ne => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::Le => "<=",
        BinaryOp::Gt => ">",
        BinaryOp::Ge => ">=",
        BinaryOp::And => "&&",
        BinaryOp::Or => "||",
        BinaryOp::BitAnd => "&",
        BinaryOp::BitOr => "|",
        BinaryOp::BitXor => "^",
        BinaryOp::Shl => "<<",
        BinaryOp::Shr => ">>",
        BinaryOp::In => "==",
    }
}
fn c_string(value: &str) -> String {
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
    )
}
