use crate::sema::CheckedModule;
/// C99 backend. The complete emitter is added incrementally; this header keeps generated C portable.
pub fn emit(_checked: &CheckedModule) -> String {
    "/* Generated by ncc. */\n#include <stdint.h>\n#include <stdbool.h>\n#include <stdio.h>\n\nint main(void) { return 0; }\n".into()
}
